



CREATE VIEW [FPV].[vApplicationStationView_bkp]
AS
WITH CombinedStations AS (
SELECT i.[DistributionGroupCode][iDistributionGroupCode]
	  ,NULL [iDistributionCode]
      ,NULL [iSociety]
      ,i.[StationID][iStationID]
      ,i.[StationName][iStationName]
      ,i.[StationCategory][iStationCategory]
	  ,i.[StationStatus][iStationStatus]
	  ,i.[CensusOrSampled][iCensusOrSampled]
	  ,i.[Diversity][iDiversity]
	  ,i.[LowRevenue][iLowRevenue]
      ,i.[GroupAdminRate][iGroupAdminRate]
      ,i.[HedgePercent][iHedgePercent]
      ,i.[PRAdminRate][iPRAdminRate]
      ,i.[IsExcluded][iIsExcluded]
	  ,i.[currentGroupAdminRate][icurrentGroupAdminRate]
	  ,i.[currentHedgePercent][icurrentHedgePercent]
	  ,i.[currentPRAdminRate][icurrentPRAdminRate]
	  ,i.[currentIsExcluded][icurrentIsExcluded]
	  ,i.[prevGroupAdminRate][iprevGroupAdminRate]
	  ,i.[prevHedgePercent][iprevHedgePercent]
	  ,i.[prevPRAdminRate][iprevPRAdminRate]
	  ,i.[prevIsExcluded][iprevIsExcluded]
	  ,i.[seedGroupAdminRate][iseedGroupAdminRate]
	  ,i.[seedHedgePercent][iseedHedgePercent]
	  ,i.[seedPRAdminRate][iseedPRAdminRate]
	  ,i.[seedIsExcluded][iseedIsExcluded]
      ,'SOURCE'[iUpdatedBy]
      ,'STATION REFRESH'[iUpdateComment]
      ,i.[SysStartTime][iSysStartTime]
      ,i.[SysEndTime][iSysEndTime]
	  ,i.[IsCurrent][MasterStationIsCurrent]
	  ,cg.[Society]
	  ,cg.[DistributionGroupCode]
	  ,cg.[DistributionCode]
	  ,cg.[CalculationGroupStatus][CalculationPeriodStatus]
	  ,cg.[CalculationPeriodStart]
	  ,cg.[CalculationPeriodEnd]
	  ,cg.[IsCurrent][CalculationGroupIsCurrent]
      ,cgs.[StationID]
      ,cgs.[StationName]
      ,cgs.[StationCategory]
	  ,cgs.[StationStatus]
      ,cgs.[GroupAdminRate]
      ,cgs.[HedgePercent]
      ,cgs.[PRAdminRate]
      ,cgs.[IsExcluded]
	  ,cgs.[currentGroupAdminRate]
	  ,cgs.[currentHedgePercent]
	  ,cgs.[currentPRAdminRate]
	  ,cgs.[currentIsExcluded]
	  ,cgs.[prevGroupAdminRate]
	  ,cgs.[prevHedgePercent]
	  ,cgs.[prevPRAdminRate]
	  ,cgs.[prevIsExcluded]
	  ,cgs.[seedGroupAdminRate]
	  ,cgs.[seedHedgePercent]
	  ,cgs.[seedPRAdminRate]
	  ,cgs.[seedIsExcluded]
      ,cgs.[UpdatedBy]
      ,cgs.[UpdateComment]
      ,cgs.[SysStartTime]
      ,cgs.[SysEndTime]
	  ,ISNULL(cgs.[IsCurrent],1)[CalculationGroupStationIsCurrent]
FROM [FPV].[vCalculationGroup] cg 
LEFT JOIN [FPV].[vMasterStation] i ON	i.[DistributionGroupCode]=cg.[DistributionGroupCode]
										AND
										i.[SysEndTime] BETWEEN cg.[SysStartTime] and cg.[SysEndTime]
FULL OUTER JOIN [FPV].[vCalculationGroupStation] cgs ON	cgs.[StationID]=i.[StationID]
															AND
															cg.[DistributionGroupCode]=cgs.[DistributionGroupCode]
															AND
															cg.[DistributionCode]=cgs.[DistributionCode]
															AND
															cg.[Society]=cgs.[Society]
															AND
															cgs.[SysStartTime] BETWEEN cg.[SysStartTime] and cg.[SysEndTime]
															AND
															i.[SysEndTime] BETWEEN cgs.[SysStartTime] AND cgs.[SysEndTime]
--WHERE (i.[IsCurrent] = 1 OR i.[IsCurrent] IS NULL)
--AND (cgs.[IsCurrent]=1 OR cgs.[IsCurrent] IS NULL)
--AND (cg.[IsCurrent]=1 OR cg.[IsCurrent] IS NULL)
)
SELECT [Society]
	  ,[iDistributionGroupCode][DistributionGroupCode]
	  ,[DistributionCode]
	  ,[CalculationPeriodStatus]
	  ,[CalculationPeriodStart]
	  ,[CalculationPeriodEnd]
	  ,[iDistributionGroupCode]
      ,[iStationID]
      ,[iStationName]
      ,[iStationCategory]
	  ,[iStationStatus]
	  ,[iCensusOrSampled]
	  ,[iDiversity]
	  ,[iLowRevenue]
      ,[iGroupAdminRate]
      ,[iHedgePercent]
      ,[iPRAdminRate]
      ,[iIsExcluded]
	  ,[icurrentGroupAdminRate]
	  ,[icurrentHedgePercent]
	  ,[icurrentPRAdminRate]
	  ,[icurrentIsExcluded]
	  ,[iprevGroupAdminRate]
	  ,[iprevHedgePercent]
	  ,[iprevPRAdminRate]
	  ,[iprevIsExcluded]
	  ,[iseedGroupAdminRate]
	  ,[iseedHedgePercent]
	  ,[iseedPRAdminRate]
      ,[iUpdatedBy]
      ,[iUpdateComment]
      ,[iSysStartTime]
      ,[iSysEndTime]
      ,[StationID]
      ,[StationName]
      ,[StationCategory]
	  ,[StationStatus]
      ,[GroupAdminRate]
      ,[HedgePercent]
      ,[PRAdminRate]
      ,[IsExcluded]
	  ,[currentGroupAdminRate]
	  ,[currentHedgePercent]
	  ,[currentPRAdminRate]
	  ,[currentIsExcluded]
	  ,[prevGroupAdminRate]
	  ,[prevHedgePercent]
	  ,[prevPRAdminRate]
	  ,[prevIsExcluded]
	  ,[seedGroupAdminRate]
	  ,[seedHedgePercent]
	  ,[seedPRAdminRate]
      ,[UpdatedBy]
      ,[UpdateComment]
      ,[SysStartTime]
      ,[SysEndTime]
	  ,[CalculationGroupIsCurrent]
	  ,[MasterStationIsCurrent]
	  ,[CalculationGroupStationIsCurrent]
	  ,case 
			when	[CalculationGroupIsCurrent] = 1
					and
					[MasterStationIsCurrent]=1
					and
					[CalculationGroupStationIsCurrent]=1 then 1
			else 0
		end [IsCurrent]
FROM	CombinedStations