



CREATE view [FPV].[vMasterMusicMinutes]
as

select 		[DistributionGroupCode]
		,[DistributionCode]
		,[Society]
		,[StationID]
		,[ProgrammeForecast]
		,[NonProgrammeForecast]
		,[CommercialForecast]
		,[TotalInPeriodForecast]
		,[LateDataForecast]
		,[TotalForecast]
		,[HighPeakPercent]
		,[LowPeakPercent]
		,[NonPeakPercent]
		,[UpdatedBy]
		,[UpdateComment]
		,[SysStartTime]
		,[SysEndTime]
		,1 [IsCurrent]
from [FPV].[MasterMusicMinutes]
union
select 		[DistributionGroupCode]
		,[DistributionCode]
		,[Society]
		,[StationID]
		,[ProgrammeForecast]
		,[NonProgrammeForecast]
		,[CommercialForecast]
		,[TotalInPeriodForecast]
		,[LateDataForecast]
		,[TotalForecast]
		,[HighPeakPercent]
		,[LowPeakPercent]
		,[NonPeakPercent]
		,[UpdatedBy]
		,[UpdateComment]
		,[SysStartTime]
		,dateadd(ms,-1,[SysEndTime])[SysEndTime]
		,0 [IsCurrent]
from [FPV].[MasterMusicMinutesHistory]