SET IDENTITY_INSERT [Control].[EntityType] ON;
GO
MERGE INTO [Control].[EntityType] AS Tgt
USING 
	(VALUES
	  --[EI],	[PETI],	[AI],	[IS],	[HMS],	[Name],										[Code],									[Description],													[Schema],				[Table],									[CreatedBy]							[CreatedDate]
		(1,		-1,		1,		1,		0,		N'Address',									N'dxaddress',							N'Address Table',												N'DATAXCHANGE',			N'DX_ADDRESS',								N'Simon.Whiteley@prsformusic.com',	SYSDATETIME()),
		(2,		-1,		1,		1,		0,		N'Country',									N'dxcountry',							N'DX Country Table',											N'DATAXCHANGE',			N'DX_COUNTRY',								N'Simon.Whiteley@prsformusic.com',	SYSDATETIME()),
		(3,		-1,		1,		1,		1,		N'StatementWorkDetail',						N'dxstmtwkdt',							N'DX Statement Work Details',									N'DATAXCHANGE',			N'DX_STMT_WKDT',							N'Simon.Whiteley@prsformusic.com',	SYSDATETIME()),
		(4,		-1,		1,		1,		0,		N'Society',									N'dxsociety',							N'DX Society Table',											N'DATAXCHANGE',			N'DX_SOCIETY',								N'Simon.Whiteley@prsformusic.com',	SYSDATETIME()),
		(6,		NULL,	1,		0,		0,		N'DimSociety',								N'dimSociety',							N'Online Statements Dim Society',								N'Warehouse',			N'DimSociety',								N'Simon.Whiteley@prsformusic.com',	SYSDATETIME()),
		(7,		NULL,	1,		0,		0,		N'DimMember',								N'dimMember',							N'Online Statements Dim Member',								N'Warehouse',			N'DimMember',								N'Simon.Whiteley@prsformusic.com',	SYSDATETIME()),
		(8,		NULL,	1,		0,		0,		N'DimDistribution',							N'dimDistribution',						N'Online Statements Dim Distribution',							N'Warehouse',			N'DimDistribution',							N'Simon.Whiteley@prsformusic.com',	SYSDATETIME()),
		(11,	NULL,	1,		0,		0,		N'FactDistributedRoyalty',					N'DistRoyalty',							N'Fact Distributed Royalty',									N'Warehouse',			N'FactDistributedRoyalty',					N'Simon.Whiteley@prsformusic.com',	SYSDATETIME()),
		(16,	-1,		1,		1,		0,		N'AffiliateStatement',						N'dxastmt',								N'Affilate Statement table',									N'DATAXCHANGE',			N'DX_A_STMT',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(17,	-1,		1,		1,		0,		N'AffiliateStatementEDetail',				N'dxastmtedet',							N'Affiliate Statement E Detail table',							N'DATAXCHANGE',			N'DX_A_STMT_EDET',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(18,	-1,		1,		1,		0,		N'AffiliateStatementFDetail',				N'dxastmtfdet',							N'Affiliate Statement F Detail table',							N'DATAXCHANGE',			N'DX_A_STMT_FDET',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(19,	-1,		1,		1,		0,		N'BroadcastRegion',							N'dxbroadcastregion',					N'DX broadcast region table',									N'DATAXCHANGE',			N'DX_BROADCAST_REGION',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(21,	-1,		1,		1,		0,		N'CAE',										N'dxcae',								N'Dx cae table',												N'DATAXCHANGE',			N'DX_CAE',									N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(22,	-1,		1,		1,		0,		N'Currency',								N'dxcurrency',							N'DX Currency table',											N'DATAXCHANGE',			N'DX_CURRENCY',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(23,	-1,		1,		1,		0,		N'Distribution',							N'dxdistribution',						N'DX Distribution table',										N'DATAXCHANGE',			N'DX_DISTRIBUTION',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(26,	-1,		1,		1,		0,		N'DistributionLoadControl',					N'dxdistributionloadcontrol',			N'DX Distribution Load Control table',							N'DATAXCHANGE',			N'DX_DISTRIBUTION_LOAD_CONTROL',			N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(27,	-1,		1,		1,		0,		N'EEAStatementDetails',						N'dxeeastmtdet',						N'DX EEA Statement Details Table',								N'DATAXCHANGE',			N'DX_EEA_STMT_DET',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(28,	-1,		1,		1,		0,		N'EEAStatementSummary',						N'dxeeastmtsumm',						N'DX EEA Statement Summary table',								N'DATAXCHANGE',			N'DX_EEA_STMT_SUMM',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(29,	-1,		1,		1,		0,		N'ElectronicStatement',						N'dxestmt',								N'DX ElectronicStatement table',								N'DATAXCHANGE',			N'DX_E_STMT',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(30,	-1,		1,		1,		0,		N'ElectronicStatementGeneralAdjustment',	N'dxestmtgnad',							N'DX Electronic statement general adjustment table',			N'DATAXCHANGE',			N'DX_E_STMT_GNAD',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(31,	-1,		1,		1,		0,		N'ElectronicStatementPaymentDetail',		N'dxestmtpymtdet',						N'DX Elecronic Statement Payment Details table',				N'DATAXCHANGE',			N'DX_E_STMT_PYMT_DET',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(32,	-1,		1,		1,		0,		N'Invoices',								N'dxinvoices',							N'DX Invoices table',											N'DATAXCHANGE',			N'DX_INVOICES',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(33,	-1,		1,		1,		0,		N'Licensees',								N'dxlicensees',							N'DX Licensees table',											N'DATAXCHANGE',			N'DX_LICENSEES',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(34,	-1,		1,		1,		0,		N'LicensingBodies',							N'dxlicensingbodies',					N'DX Licensing Bodies table',									N'DATAXCHANGE',			N'DX_LICENSING_BODIES',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(35,	-1,		1,		1,		0,		N'MajorMember',								N'dxmajormember',						N'DX Major member table',										N'DATAXCHANGE',			N'DX_MAJOR_MEMBER',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(36,	-1,		1,		1,		0,		N'Membership',								N'dxmembership',						N'DX Membership tables',										N'DATAXCHANGE',			N'DX_MEMBERSHIP',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(37,	-1,		1,		1,		0,		N'MembershipType',							N'dxmembershiptype',					N'DX Membership Type table',									N'DATAXCHANGE',			N'DX_MEMBERSHIP_TYPE',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(40,	-1,		1,		1,		0,		N'MemberSourceSocieties',					N'dxmembersourcesocieties',				N'DX Member Source Societies table',							N'DATAXCHANGE',			N'DX_MEMBER_SOURCE_SOCIETIES',				N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(41,	-1,		1,		1,		0,		N'MemberStatements',						N'dxmemberstatements',					N'DX Member Statements table',									N'DATAXCHANGE',			N'DX_MEMBER_STATEMENTS',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(42,	-1,		1,		1,		0,		N'StatementInstructionLicensingBodies',		N'dxmvstmtinstrlibos',					N'DX Statement Instruction Licensing Bodies table',				N'DATAXCHANGE',			N'DX_MV_STMT_INSTR_LIBOS',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(43,	-1,		1,		1,		0,		N'ProductTypes',							N'dxproducttypes',						N'DX Product Types table',										N'DATAXCHANGE',			N'DX_PRODUCT_TYPES',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(44,	-1,		1,		1,		0,		N'PaymentInstruction',						N'dxpymtinstruction',					N'DX PaymentInstruction table',									N'DATAXCHANGE',			N'DX_PYMT_INSTRUCTION',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(45,	-1,		1,		1,		0,		N'PaperStatement',							N'dxpstmt',								N'DX Paper Statement table',									N'DATAXCHANGE',			N'DX_P_STMT',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(46,	-1,		1,		1,		0,		N'PaperStatementAccountDetails',			N'dxpstmtaccdet',						N'DX Paper Statement Account Details table',					N'DATAXCHANGE',			N'DX_P_STMT_ACC_DET',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(47,	-1,		1,		1,		0,		N'PaperStatementCommissionInvoice',			N'dxpstmtcomminvoice',					N'DX Paper Statement Commission Invoice table',					N'DATAXCHANGE',			N'DX_P_STMT_COMM_INVOICE',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(48,	-1,		1,		1,		0,		N'PaperStatementGeneralAdjustmentLines',	N'dxpstmtgad',							N'DX Paper Statement General Adjustment Lines table',			N'DATAXCHANGE',			N'DX_P_STMT_GAD',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(49,	-1,		1,		1,		0,		N'PaperStatementNOPEarningLines',			N'dxpstmtnopearndet',					N'DX Paper Statement NOP Earning Lines table',					N'DATAXCHANGE',			N'DX_P_STMT_NOP_EARN_DET',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(50,	-1,		1,		1,		0,		N'PaperStatementNOPPaymentLines',			N'dxpstmtnoppymtdet',					N'DX Paper Statement NOP Payment Lines table',					N'DATAXCHANGE',			N'DX_P_STMT_NOP_PYMT_DET',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(55,	-1,		1,		1,		0,		N'PaperStatementTopFiveEarners',			N'dxpstmttopfiveearners',				N'DX Paper Statement Top Five Eaners table',					N'DATAXCHANGE',			N'DX_P_STMT_TOP_FIVE_EARNERS',				N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(56,	-1,		1,		1,		0,		N'PaperStatementVATLines',					N'dxpstmtvtdt',							N'DX Paper Stateent VAT Lines table',							N'DATAXCHANGE',			N'DX_P_STMT_VTDT',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(57,	-1,		1,		1,		0,		N'RollupMember',							N'dxrollupmember',						N'DX Rollup Member table',										N'DATAXCHANGE',			N'DX_ROLLUP_MEMBER',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(58,	-1,		1,		1,		0,		N'ScottishPostCodes',						N'dxscottishpostcodes',					N'DX Scottish PostCodes table',									N'DATAXCHANGE',			N'DX_SCOTTISH_POST_CODES',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(59,	-1,		1,		1,		0,		N'ServiceTypes',							N'dxservicetypes',						N'DX Service Types table',										N'DATAXCHANGE',			N'DX_SERVICE_TYPES',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(60,	-1,		1,		1,		0,		N'SocietyUsageLink',						N'dxsocietyusagelink',					N'DX Society Usage Link table',									N'DATAXCHANGE',			N'DX_SOCIETY_USAGE_LINK',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(63,	-1,		1,		1,		0,		N'StatementInstruction',					N'dxstatementinstruction',				N'DX Statement Instruction table',								N'DATAXCHANGE',			N'DX_STATEMENT_INSTRUCTION',				N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(64,	-1,		1,		1,		0,		N'StatementRun',							N'dxstatementrun',						N'DX Statement Run table',										N'DATAXCHANGE',			N'DX_STATEMENT_RUN',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(65,	-1,		1,		1,		0,		N'StandardTaxRate',							N'dxstdtaxrate',						N'DX Standard Tax Rate table',									N'DATAXCHANGE',			N'DX_STD_TAX_RATE',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(66,	-1,		1,		1,		0,		N'StatementInstructionSocieties',			N'dxstinsocieties',						N'DX Statement Instruction Societies table',					N'DATAXCHANGE',			N'DX_STIN_SOCIETIES',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(67,	-1,		1,		1,		0,		N'StatementAddition',						N'dxstmtaddt',							N'DX Statement addition table',									N'DATAXCHANGE',			N'DX_STMT_ADDT',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(68,	-1,		1,		1,		0,		N'StatementDetails',						N'dxstmtdetail',						N'DX Statement Detail table',									N'DATAXCHANGE',			N'DX_STMT_DETAIL',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(69,	-1,		1,		1,		0,		N'StatementDummyAddress',					N'dxstmtdummyaddress',					N'DX Statement Dummy Address table',							N'DATAXCHANGE',			N'DX_STMT_DUMMY_ADDRESS',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(70,	-1,		1,		1,		0,		N'Territory',								N'dxterritorytis',						N'DX Territory table',											N'DATAXCHANGE',			N'DX_TERRITORY_TIS',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(71,	-1,		1,		1,		0,		N'UsageCategories',							N'dxusagecategories',					N'DX Usage Categories table',									N'DATAXCHANGE',			N'DX_USAGE_CATEGORIES',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(72,	-1,		1,		1,		0,		N'UsageGroup',								N'dxusagegroup',						N'DX Usage Group table',										N'DATAXCHANGE',			N'DX_USAGE_GROUP',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(73,	-1,		1,		1,		0,		N'UsageGroupSummary',						N'dxusagegroupsumm',					N'DX Usage Group Summary table',								N'DATAXCHANGE',			N'DX_USAGE_GROUP_SUMM',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(74,	-1,		1,		1,		0,		N'UsageGroupType',							N'dxusagegrouptype',					N'DX Usage Group Type table',									N'DATAXCHANGE',			N'DX_USAGE_GROUP_TYPE',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(75,	-1,		1,		1,		0,		N'WithheldSocietyTax',						N'dxwithheldsocietytax',				N'DX Withheld society tax table',								N'DATAXCHANGE',			N'DX_WITHHELD_SOCIETY_TAX',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(76,	-1,		1,		1,		0,		N'PaperStatementAccountShare',				N'dxpstmtaccshare',						N'DX Paper Statement Account Share table',						N'DATAXCHANGE',			N'DX_P_STMT_ACC_SHARE',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(77,	NULL,	1,		0,		0,		N'AdjustmentLine',							N'AdjustmentLine',						N'Online Statements Adjustment Line',							N'Warehouse',			N'AdjustmentLine',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(78,	NULL,	1,		0,		0,		N'CommissionInvoice',						N'CommissionInvoice',					N'OnlineStatements Commission Invoice',							N'Warehouse',			N'CommissionInvoice',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(84,	NULL,	1,		0,		0,		N'CommissionInvoiceLine',					N'CommInvoiceLine',						N'Online Statements Comm Invoice Line',							N'Warehouse',			N'CommissionInvoiceLine',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(85,	NULL,	1,		0,		0,		N'DimAdjustmentReason',						N'dimAdjustmentReason',					N'Online Statements Adjustment Reason',							N'Warehouse',			N'DimAdjustmentReason',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(86,	NULL,	1,		0,		0,		N'DimBroadcaster',							N'dimBroadcaster',						N'Online Statements Dim Broadcaster',							N'Warehouse',			N'DimBroadcaster',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(87,	NULL,	1,		0,		0,		N'DimCountry',								N'dimCountry',							N'Online Statements Dim Country',								N'Warehouse',			N'DimCountry',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(90,	NULL,	1,		0,		0,		N'DimDate',									N'dimDate',								N'Online Statements Dim Date',									N'Warehouse',			N'DimDate',									N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(92,	NULL,	1,		0,		0,		N'DimInterestedParty',						N'dimInterestedParty',					N'Online Statements Dim Interested Party',						N'Warehouse',			N'DimInterestedParty',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(93,	NULL,	1,		0,		0,		N'DimInvoice',								N'dimInvoice',							N'Online Statements Dim Invoice',								N'Warehouse',			N'DimInvoice',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(94,	NULL,	1,		0,		0,		N'DimLicensingBody',						N'dimLicensingBody',					N'Online Statements Dim Licensing Body',						N'Warehouse',			N'DimLicensingBody',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(96,	NULL,	1,		0,		0,		N'DimProduct',								N'dimProduct',							N'Online Statements Dim Product',								N'Warehouse',			N'DimProduct',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(97,	NULL,	1,		0,		0,		N'DimRecording',							N'dimRecording',						N'Online Statements Dim Recording',								N'Warehouse',			N'DimRecording',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(98,	NULL,	1,		0,		0,		N'DimRoleType',								N'dimRoleType',							N'Online Statements Dim Role Type',								N'Warehouse',			N'DimRoleType',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(105,	NULL,	1,		0,		0,		N'DimRoyaltyClassification',				N'dimRoyaltyClass',						N'Dim Royalty Classification',									N'Warehouse',			N'DimRoyaltyClassification',				N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(106,	NULL,	1,		0,		0,		N'DimUsageClassification',					N'dimUsageClass',						N'Dim Usage Classification',									N'Warehouse',			N'DimUsageClassification',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(107,	NULL,	1,		0,		0,		N'DimUsageGroup',							N'dimUsageGroup',						N'Online Statements Dim Usage Group',							N'Warehouse',			N'DimUsageGroup',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(108,	NULL,	1,		0,		0,		N'DimWork',									N'dimWork',								N'Online Stateents Dim Work',									N'Warehouse',			N'DimWork',									N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(110,	NULL,	1,		0,		0,		N'GeneralRoyaltyLine',						N'GeneralRoyaltyLine',					N'General Loyalty Line',										N'Warehouse',			N'GeneralRoyaltyLine',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(112,	NULL,	1,		0,		0,		N'NopEarningLine',							N'NopEarningLine',						N'Nop Earning Line',											N'Warehouse',			N'NopEarningLine',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(113,	NULL,	1,		0,		0,		N'NopNoteText',								N'NopNoteText',							N'Nop Note Text ',												N'Warehouse',			N'NopNoteText',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(114,	NULL,	1,		0,		0,		N'NopPaymentLine',							N'NopPaymentLine',						N'Nop Payment Line',											N'Warehouse',			N'NopPaymentLine',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(115,	NULL,	1,		0,		0,		N'NoteText',								N'NoteText',							N'Note Text',													N'Warehouse',			N'NoteText',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(116,	NULL,	1,		0,		0,		N'OnlineStatement',							N'OnlineStatement',						N'Online Statement',											N'Warehouse',			N'OnlineStatement',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(117,	NULL,	1,		0,		0,		N'SourceStatement',							N'SourceStatement',						N'Source Statement',											N'Warehouse',			N'SourceStatement',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(119,	NULL,	1,		0,		0,		N'StatementLicensingBody',					N'StatemtLicensingBody',				N'Statement Licensing Body',									N'Warehouse',			N'StatementLicensingBody',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(120,	NULL,	1,		0,		0,		N'ThirdPartyStatementGroup',				N'ThrdPrtyStmtGroup',					N'Third Party Statement Group',									N'Warehouse',			N'ThirdPartyStatementGroup',				N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(126,	NULL,	1,		0,		0,		N'ThirdPartyStatementGroupOnlineStatement',	N'ThrdPrtyStmtGrpOlSt',					N'Third Party Statement Group Online Statement',				N'Warehouse',			N'ThirdPartyStatementGroupOnlineStatement',	N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(127,	NULL,	1,		0,		0,		N'UsageGroupRoyaltyLine',					N'UsageGrpRoyLine',						N'Usage Group Royalty Line',									N'Warehouse',			N'UsgaeGroupRoyaltyLine',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(128,	NULL,	1,		0,		0,		N'VATInvoice',								N'VATInvoice',							N'VATInvoice',													N'Warehouse',			N'VATInvoice',								N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(129,	NULL,	1,		0,		0,		N'VATInvoiceLine',							N'VATInvoiceLine',						N'VATInvoiceLine',												N'Warehouse',			N'VATInvoiceLine',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(130,	NULL,	1,		0,		0,		N'DimWorkAttributes',						N'dimWorkAttributes',					N'Online Statements Dim Work Attributes',						N'Warehouse',			N'DimWorkAttributes',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(131,	NULL,	1,		0,		0,		N'TempDistributedRoyalty',					N'TempDistributedRoyalty',				N'Temp Distributed Royalty',									N'Transform',			N'TempDistributedRoyalty',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(132,	NULL,	1,		0,		0,		N'TempDistributedRoyaltyWkdt',				N'TempDistributedRoyaltyWkdt',			N'Temp Distributed Royalty Wkdt',								N'Transform',			N'TempDistributedRoyaltyWkdt',				N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(133,	NULL,	1,		0,		0,		N'TempDistributedRoyaltyAddt',				N'TempDistributedRoyaltyAddt',			N'Temp Distributed Royalty Addt',								N'Transform',			N'TempDistributedRoyaltyAddt',				N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(134,	NULL,	1,		0,		0,		N'TempStatement',							N'TempStatement',						N'Temp Statement',												N'Transform',			N'TempStatement',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(135,	NULL,	1,		0,		0,		N'TempStatementShare',						N'TempStatementShare',					N'Temp Statement Share',										N'Transform ',			N'TempStatementShare',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(137,	NULL,	1,		1,		0,		N'ReportsText',								N'reportstext',							N'Reports Text',												N'DATAXCHANGE',			N'REPORTS_TEXT',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(138,	NULL,	1,		1,		0,		N'ReportTypes',								N'reporttypes',							N'Report Types',												N'DATAXCHANGE',			N'REPORT_TYPES',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(139,	NULL,	1,		1,		0,		N'StatementInstrumentLiboList',				N'dxstmtinstrlibolist',					N'StatementInstrumentLicensingBodyList table',					N'DATAXCHANGE',			N'DX_STMT_INSTR_LIBO_LIST',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(140,	NULL,	2,		0,		0,		N'BroadcastDataQualityFormat5',				N'brcdqformat5',						N'Broadcast DataQuality Format5',								N'BRCDataQuality',		N'BRC_DQ_Format5',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(143,	NULL,	2,		0,		0,		N'BroadcastDataQualityFormat50',			N'brcdqformat50',						N'Broadcast DataQuality Format50',								N'BRCDataQuality',		N'BRC_DQ_Format50',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(144,	NULL,	2,		0,		0,		N'BroadcastDataQualityFormat52',			N'brcdqformat52',						N'Broadcast DataQuality Format52',								N'BRCDataQuality',		N'BRC_DQ_Format52',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(146,	NULL,	2,		0,		0,		N'BroadcastDataQualityFormat303',			N'brcdqformat303',						N'Broadcast DataQuality Format303',								N'BRCDataQuality',		N'BRC_DQ_Format303',						N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(147,	NULL,	2,		0,		0,		N'BroadcastDataQualityFormat51',			N'brcdqformat51',						N'Broadcast DataQuality Format51',								N'BRCDataQuality',		N'BRC_DQ_Format51',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(148,	NULL,	2,		0,		0,		N'BroadcastDataQualityFormat51a',			N'brcdqformat51a',						N'Broadcast DataQuality Format51a',								N'BRCDataQuality',		N'BRC_DQ_Format51a',						N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(149,	NULL,	2,		0,		0,		N'BroadcastDataQualityFormatS1',			N'brcdqformats1',						N'Broadcast DataQuality FormatS1',								N'BRCDataQuality',		N'BRC_DQ_FormatS1',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(150,	NULL,	2,		0,		0,		N'BroadcastDataQualityFormatS2',			N'brcdqformats2',						N'Broadcast DataQuality FormatS2',								N'BRCDataQuality',		N'BRC_DQ_FormatS2',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(151,	NULL,	1,		0,		0,		N'TempFactDistributedRoyalty',				N'TempFactDistributedRoyalty',			N'Temp Fact Distributed Royalty',								N'Transform',			N'TempFactDistributedRoyalty',				N'Chris.Ellis@prsformusic.com',		SYSDATETIME()),
		(153,	NULL,	1,		1,		0,		N'StatementMembershipLiboList',				N'dxstmtmbrlibolist',					N'StatementMembershipLicensingBodyList table',					N'DATAXCHANGE',			N'DX_STMT_MBR_LIBO_LIST',					N'Jonathan.Myers@prsformusic.com',	SYSDATETIME()),
		(154,	NULL,	1,		0,		0,		N'TempPayeeStatement',						N'TempPayeeStatement',					N'Temp Payee Statement table',									N'Transform',			N'TempPayeeStatement',						N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(155,	NULL,	1,		0,		0,		N'TempMbrStatement',						N'TempMbrStatement',					N'Temp Mbr Statement table',									N'Transform',			N'TempMbrStatement',						N'vandana.bangera@prsformusic.com',	SYSDATETIME()),		
		(157,	NULL,	3,		1,		0,		N'Dim File',								N'prbidimfile',							N'Oracle Dim_File table',										N'PRBI_DW',				N'DIM_FILE',								N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(158,	NULL,	3,		1,		0,		N'Dim Third Party Tree',					N'prbidimthirdpartytree',				N'Oracle Dim_ThirdPartyTree table',								N'PRBI_DW',				N'DIM_THIRD_PARTY_TREE',					N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(159,	NULL,	3,		0,		0,		N'Dim Date',								N'prbidimdate',							N'Oracle Dim_Date table',										N'PRBI_DW',				N'DIM_DATE',								N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(160,	NULL,	3,		1,		0,		N'Dim Production',							N'prbidimproduction',					N'Oracle Dim_Production table',									N'PRBI_DW',				N'DIM_PRODUCTION',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(163,	NULL,	3,		1,		0,		N'Dim Broadcaster',							N'prbidimbroadcaster',					N'Oracle Dim_Broadcaster table',								N'PRBI_DW',				N'DIM_BROADCASTER',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(164,	NULL,	3,		1,		0,		N'Dim Usage Of Work Status',				N'prbidimusageofworkstatus',			N'Oracle Dim_Usage_Of_Work_Status table',						N'PRBI_DW',				N'DIM_USAGE_OF_WORK_STATUS',				N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(169,	NULL,	3,		1,		0,		N'Dim Right Type',							N'prbidimrighttype',					N'Oracle Dim_Right_Type table',									N'PRBI_DW',				N'DIM_RIGHT_TYPE',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(172,	NULL,	3,		1,		0,		N'Dim Work',								N'prbidimwork',							N'Oracle Dim_Work table',										N'PRBI_DW',				N'DIM_WORK',								N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(173,	NULL,	3,		1,		0,		N'Dim Transmission Status',					N'prbidimtransmissionstatus',			N'Oracle Dim_Transmission_Status table',						N'PRBI_DW',				N'DIM_TRANSMISSION_STATUS',					N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(174,	NULL,	3,		1,		0,		N'Dim Usage Distribution Code',				N'prbidimusagedistributioncode',		N'Oracle Dim_Usage_Distribution_Code table',					N'PRBI_DW',				N'DIM_USAGE_DISTRIBUTION_CODE',				N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(177,	NULL,	1,		0,		0,		N'TempMbrStatementSociety',					N'TempMbrStatementSociety',				N'Temp Mbr Statement Society table',							N'Transform',			N'TempMbrStatementSociety',					N'jonathan.myers@prsformusic.com',	SYSDATETIME()),
		(178,	NULL,	3,		1,		0,		N'Dim Music Origin',						N'prbidimmusicorigin',					N'Oracle Dim_Music_Origin table',								N'PRBI_DW',				N'DIM_MUSIC_ORIGIN',						N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(179,	NULL,	3,		0,		0,		N'DimRightType',							N'DimRightType',						N'DimRightType table',											N'PipelineWarehouse',	N'DimRightType',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(200,	-1,		4,		1,		0,		N'CodaBalance',								N'codabalance',							N'CODA oas_balances',											N'CodaStaging',			N'Coda_Balance',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(201,	-1,		4,		1,		0,		N'CodaCompany',								N'codacompany',							N'CODA oas_company',											N'CodaStaging',			N'Coda_Company',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(202,	-1,		4,		1,		0,		N'CodaDocument',							N'codadocument',						N'CODA oas_document',											N'CodaStaging',			N'Coda_Document',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(203,	-1,		4,		1,		0,		N'CodaTransactions',						N'codatransactions',					N'CODA Transactions oas_head joined oas_list',					N'CodaStaging',			N'Coda_Transactions',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(204,	-1,		4,		1,		0,		N'CodaElement',								N'codaelement',							N'CODA oas_element',											N'CodaStaging',			N'Coda_Element',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(205,	-1,		4,		1,		0,		N'CodaGroupList',							N'codagrouplist',						N'CODA oas_grplist joined oas_group',							N'CodaStaging',			N'Coda_GroupList',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(206,	-1,		4,		1,		0,		N'CodaTM1Budgets',							N'codatm1budgets',						N'TM1 Budgets csv export',										N'CodaStaging',			N'Coda_TM1Budgets',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(207,	-1,		4,		1,		0,		N'CodaTM1Forecasts',						N'codatm1forecasts',					N'TM1 Forecasts csv export',									N'CodaStaging',			N'Coda_TM1Forecasts',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(208,	-1,		4,		1,		0,		N'CodaMDS_EL1',								N'codamdsel1',							N'CODA MDS 2016 EL1 export',									N'CodaStaging',			N'Coda_MDS_EL1',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(209,	-1,		4,		1,		0,		N'CodaMDS_EL2',								N'codamdsel2',							N'CODA MDS 2016 EL2 export',									N'CodaStaging',			N'Coda_MDS_EL2',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(210,	-1,		4,		1,		0,		N'CodaMDS_EL12',							N'codamdsel12',							N'CODA MDS 2016 EL1 + EL2 export',								N'CodaStaging',			N'Coda_MDS_EL12',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(211,	-1,		4,		1,		0,		N'CodaUsrCapab',							N'codausrcapab',						N'CODA USer Capability Security Details',						N'CodaStaging',			N'Coda_UsrCapab',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(212,	-1,		4,		1,		0,		N'CodaMDS_EL123',							N'codamdsel123',						N'CODA MDS 2016 EL1 + EL2 +  EL3 export',						N'CodaStaging',			N'Coda_MDS_EL123',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(220,	-1,		4,		0,		0,		N'FactBalance',								N'factcodabalance',						N'Finance DataMart oas_balances',								N'CodaWarehouse',		N'Fact_Balance',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(221,	-1,		4,		0,		0,		N'DimCompany',								N'dimcompany',							N'Finance DataMart company dimension',							N'CodaWarehouse',		N'Dim_Company',								N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(222,	-1,		4,		0,		0,		N'DimDocument',								N'dimdocument',							N'Finance DataMart document dimension',							N'CodaWarehouse',		N'Dim_Document',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(223,	-1,		4,		0,		0,		N'FactTransactions',						N'facttransactions',					N'Finance DataMart Transactions',								N'CodaWarehouse',		N'Fact_Transactions',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(224,	-1,		4,		0,		0,		N'DimAccountsEL1',							N'dimaccountsel1',						N'Finance DataMart Coda EL1 Accounts Dimension',				N'CodaWarehouse',		N'Dim_Accounts_EL1',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(225,	-1,		4,		0,		0,		N'DimAccountsEL2',							N'dimaccountsel2',						N'Finance DataMart Coda EL2 Accounts Dimension',				N'CodaWarehouse',		N'Dim_Accounts_EL2',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(226,	-1,		4,		0,		0,		N'DimAccountsEL3',							N'dimaccountsel3',						N'Finance DataMart Coda EL3 Accounts Dimension',				N'CodaWarehouse',		N'Dim_Accounts_EL3',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(227,	-1,		4,		0,		0,		N'DimAccountsEL4',							N'dimaccountsel4',						N'Finance DataMart Coda EL4 Accounts Dimension',				N'CodaWarehouse',		N'Dim_Accounts_EL4',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(228,	-1,		4,		0,		0,		N'DimAccountsEL5',							N'dimaccountsel5',						N'Finance DataMart Coda EL5 Accounts Dimension',				N'CodaWarehouse',		N'Dim_Accounts_EL5',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(229,	-1,		4,		0,		0,		N'DimAccountsEL6',							N'dimaccountsel6',						N'Finance DataMart Coda EL6 Accounts Dimension',				N'CodaWarehouse',		N'Dim_Accounts_EL6',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(230,	-1,		4,		0,		0,		N'FactTM1Planning',							N'codatm1planning',						N'TM1 Budgets csv export',										N'CodaWarehouse',		N'Coda_TM1Planning',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(231,	-1,		4,		0,		0,		N'DimDMMappings',							N'dimdmmappings',						N'Finance DataMart Coda EL1+2+3 Dim_DM_Mappings',				N'CodaWarehouse',		N'Dim_DM_Mappings',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(232,	-1,		4,		0,		0,		N'DimCustomerScheme',						N'dimcustomerscheme',					N'EL1+2 Dim_CustomerScheme',									N'CodaWarehouse',		N'Dim_CustomerScheme',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(300,	NULL,	3,		0,		0,		N'DimBroadcaster',							N'DimBroadcaster',						N'Play to Pay DimBroadcaster table',							N'PipelineWarehouse',	N'DimBroadcaster',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(301,	NULL,	3,		0,		0,		N'DimFile',									N'DimFile',								N'Play to Pay DimFile table',									N'PipelineWarehouse',	N'DimFile',									N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(302,	NULL,	3,		0,		0,		N'DimMusicOrigin',							N'DimMusicOrigin',						N'Play to Pay DimMusicOrigin table',							N'PipelineWarehouse',	N'DimMusicOrigin',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(303,	NULL,	3,		0,		0,		N'DimProduction',							N'DimProduction',						N'Play to Pay DimProduction table',								N'PipelineWarehouse',	N'DimProduction',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(304,	NULL,	3,		0,		0,		N'DimThirdPartyTree',						N'DimThirdPartyTree',					N'Play to Pay DimThirdPartyTree table',							N'PipelineWarehouse',	N'DimThirdPartyTree',						N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(305,	NULL,	3,		0,		0,		N'DimTransmissionStatus',					N'DimTransmissionStatus',				N'Play to Pay DimTransmissionStatus table',						N'PipelineWarehouse',	N'DimTransmissionStatus',					N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(306,	NULL,	3,		0,		0,		N'DimUsageDistributionCode',				N'DimUsageDistributionCode',			N'Play to Pay DimUsageDistributionCode table',					N'PipelineWarehouse',	N'DimUsageDistributionCode',				N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(307,	NULL,	3,		0,		0,		N'DimUsageOfWorkStatus',					N'DimUsageOfWorkStatus',				N'Play to Pay DimUsageOfWorkStatus table',						N'PipelineWarehouse',	N'DimUsageOfWorkStatus',					N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(308,	NULL,	3,		0,		0,		N'DimWork',									N'DimWork',								N'Play to Pay DimWork table',									N'PipelineWarehouse',	N'DimWork',									N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(309,	NULL,	3,		0,		0,		N'FactUsageOfWork',							N'FactUsageOfWork',						N'Play to Pay FactUsageOfWork table',							N'PipelineWarehouse',	N'FactUsageOfWork',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(310,	NULL,	3,		1,		0,		N'Dim Time',								N'prbidimtime',							N'Oracle Dim_Time table',										N'PRBI_DW',				N'DIM_TIME',								N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(311,	NULL,	3,		0,		0,		N'DimTime',									N'DimTime',								N'Play to Pay DimTime table',									N'PipelineWarehouse',	N'DimTime',									N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(312,	NULL,	3,		1,		1,		N'FactUsageOfWorkPl',						N'prbifactusageofworkpl',				N'Oracle Fact_Usage_Of_Work table',								N'PRBI_DW',				N'FACT_USAGE_OF_WORK_PL',					N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(313,	NULL,	3,		1,		1,		N'FactUsageOfWorkWl',						N'prbifactusageofworkwl',				N'Oracle Fact_Usage_Of_Work table',								N'PRBI_DW',				N'FACT_USAGE_OF_WORK_WL',					N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(314,	NULL,	3,		0,		0,		N'TempFactUsageOfWorkExisting',				N'prbitempfactusageofworkexisting',		N'Oracle Fact_Usage_Of_Work table',								N'PipelineTransform',	N'TempFactUsageOfWorkExisting',				N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(315,	NULL,	3,		0,		0,		N'TempFactUsageOfWorkNew',					N'prbitempfactusageofworknew',			N'Oracle Fact_Usage_Of_Work table',								N'PipelineTransform',	N'TempFactUsageOfWorkNew',					N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(316,	NULL,	3,		0,		0,		N'TempFactUsageOfWorkChanged',				N'prbitempfactusageofworkchanged',		N'Oracle Fact_Usage_Of_Work table',								N'PipelineTransform',	N'TempFactUsageOfWorkChanged',				N'emma.stewart@prsformusic.com',	SYSDATETIME()),			
		(317,	NULL,	3,		1,		0,		N'Dim Role Type',							N'prbidimroletype',						N'Oracle DIM_ROLE_TYPE table',									N'PRBI_DW',				N'DIM_ROLE_TYPE',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(318,	NULL,	3,		1,		0,		N'Dim Ownership Ip',						N'prbidimownershipip',					N'Oracle DIM_OWNERSHIP_IP table',								N'PRBI_DW',				N'DIM_OWNERSHIP_IP',						N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(319,	NULL,	3,		1,		0,		N'Fact Work Ownership Ip',					N'prbifactworkownershipip',				N'Oracle FACT_WORK_OWNERSHIP_IP table',							N'PRBI_DW',				N'FACT_WORK_OWNERSHIP_IP',					N'emma.stewart@prsformusic.com',	SYSDATETIME()),	
		(320,	NULL,	3,		0,		0,		N'DimRoleType',								N'DimRoleType',							N'Play to Pay DimRoleType table',								N'PipelineWarehouse',	N'DimRoleType',								N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(321,	NULL,	3,		0,		0,		N'DimOwnershipIp',							N'DimOwnershipIp',						N'Play to Pay DimOwnershipIp table',							N'PipelineWarehouse',	N'DimOwnershipIp',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(322,	NULL,	3,		0,		0,		N'FactWorkOwnershipIp',						N'FactWorkOwnershipIp',					N'Play to Pay FactWorkOwnershipIp table',						N'PipelineWarehouse',	N'FactWorkOwnershipIp',						N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(324,	NULL,	3,		1,		0,		N'Dim Broadcaster Attributes',				N'prbidimbroadcasterattributes',		N'Oracle Dim Broadcaster Attributes Table',						N'PRBI_DW',				N'DIM_BROADCASTER_ATTRIBUTES',				N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(325,	NULL,	3,		1,		0,		N'Dim Tune Code Group',						N'prbidimtunecodegroup',				N'Oracle Dim Tune Code Group Table',							N'PRBI_DW',				N'DIM_TUNE_CODE_GROUP',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(326,	NULL,	3,		1,		0,		N'Dim Music Classification',				N'prbidimmusicclassification',			N'Oracle Dim Music Classification Table',						N'PRBI_DW',				N'DIM_MUSIC_CLASSIFICATION',				N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(327,	NULL,	3,		1,		0,		N'Dim Usage Classification',				N'prbidimusageclassification',			N'Oracle Dim Usage Classification Table',						N'PRBI_DW',				N'DIM_USAGE_CLASSIFICATION',				N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(328,	NULL,	3,		1,		0,		N'Dim Mech Usage Classification',			N'prbidimmechusageclassification',		N'Oracle Dim Mech Usage Classification Table',					N'PRBI_DW',				N'DIM_MECH_USAGE_CLASSIFICATION',			N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(329,	NULL,	3,		1,		0,		N'Dim MCPS Licence Type',					N'prbidimmcpslicencetype',				N'Oracle Dim MCPS Licence Type Table',							N'PRBI_DW',				N'DIM_MCPS_LICENCE_TYPE',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(330,	NULL,	3,		1,		0,		N'Dim Bro Attribute Purpose   ',			N'prbidimbroattributepurpose',			N'Oracle Dim Bro Attribute Purpose    Table',					N'PRBI_DW',				N'DIM_BRO_ATTRIBUTE_PURPOSE   ',			N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(331,	NULL,	3,		1,		0,		N'Fact Bro Attributes',						N'prbifactbroattributes',				N'Oracle Fact Bro Attributes Table',							N'PRBI_DW',				N'FACT_BRO_ATTRIBUTES',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),	
		(332,	NULL,	3,		1,		0,		N'Fact Bro MCPS Licence Type',				N'prbifactbromcpslicencetype',			N'Oracle Fact Bro MCPS Licence Type Table',						N'PRBI_DW',				N'FACT_BRO_MCPS_LICENCE_TYPE',				N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(333,	NULL,	3,		1,		0,		N'Fact Bro Right Type',						N'prbifactbrorighttype',				N'Oracle Fact Bro Right Type Table',							N'PRBI_DW',				N'FACT_BRO_RIGHT_TYPE',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(334,	NULL,	3,		1,		0,		N'Fact Tune Code Group',					N'prbifacttunecodegroup',				N'Oracle Fact Tune Code Group Table',							N'PRBI_DW',				N'FACT_TUNE_CODE_GROUP',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(335,	NULL,	3,		1,		0,		N'Dim Ownership CAE Group',					N'prbidimownershipcaegroup',			N'Oracle Dim Ownership CAE Group Table',						N'PRBI_DW',				N'DIM_OWNERSHIP_CAE_GROUP',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(336,	NULL,	3,		1,		0,		N'Fact Ownership CAE Group',				N'prbifactownershipcaegroup',			N'Oracle Fact Ownership CAE Group Table',						N'PRBI_DW',				N'FACT_OWNERSHIP_CAE_GROUP',				N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(337,	NULL,	3,		1,		0,		N'Fact Bro Sample Date',					N'prbifactbrosampledate',				N'Oracle Fact Bro Sample Date Table',							N'PRBI_DW',				N'FACT_BRO_SAMPLE_DATE',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(338,	NULL,	3,		0,		0,		N'DimBroadcasterAttributes',				N'DimBroadcasterAttributes',			N'Play to Pay Dim Broadcaster Attributes Table',				N'PipelineWarehouse',	N'DimBroadcasterAttributes',				N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(339,	NULL,	3,		0,		0,		N'DimTuneCodeGroup',						N'DimTuneCodeGroup',					N'Play to Pay Dim Tune Code Group Table',						N'PipelineWarehouse',	N'DimTuneCodeGroup',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(340,	NULL,	3,		0,		0,		N'DimMusicClassification',					N'DimMusicClassification',				N'Play to Pay Dim Music Classification Table',					N'PipelineWarehouse',	N'DimMusicClassification',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(341,	NULL,	3,		0,		0,		N'DimUsageClassification',					N'DimUsageClassification',				N'Play to Pay Dim Usage Classification Table',					N'PipelineWarehouse',	N'DimUsageClassification',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(342,	NULL,	3,		0,		0,		N'DimMechUsageClassification',				N'DimMechUsageClassification',			N'Play to Pay Dim Mech Usage Classification Table',				N'PipelineWarehouse',	N'DimMechUsageClassification',				N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(343,	NULL,	3,		0,		0,		N'DimMCPSLicenceType',						N'DimMCPSLicenceType',					N'Play to Pay Dim MCPS Licence Type Table',						N'PipelineWarehouse',	N'DimMCPSLicenceType',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(344,	NULL,	3,		0,		0,		N'DimBroAttributePurpose',					N'DimBroAttributePurpose',				N'Play to Pay Dim Bro Attribute Purpose Table',					N'PipelineWarehouse',	N'DimBroAttributePurpose',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(345,	NULL,	3,		0,		0,		N'FactBroAttributes',						N'FactBroAttributes',					N'Play to Pay Fact Bro Attributes Table',						N'PipelineWarehouse',	N'FactBroAttributes',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(346,	NULL,	3,		0,		0,		N'FactBroSampleDate',						N'FactBroSampleDate',					N'Play to Pay Fact Bro Sample Date Table',						N'PipelineWarehouse',	N'FactBroSampleDate',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(347,	NULL,	3,		0,		0,		N'FactBroMCPSLicenceType',					N'FactBroMCPSLicenceType',				N'Play to Pay Fact Bro MCPS Licence Type Table',				N'PipelineWarehouse',	N'FactBroMCPSLicenceType',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(348,	NULL,	3,		0,		0,		N'FactBroRightType',						N'FactBroRightType',					N'Play to Pay Fact Bro Right Type Table',						N'PipelineWarehouse',	N'FactBroRightType',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(349,	NULL,	3,		0,		0,		N'FactTuneCodeGroup',						N'FactTuneCodeGroup',					N'Play to Pay Fact Tune Code Group Table',						N'PipelineWarehouse',	N'FactTuneCodeGroup',						N'tim.firmin@prsformusic.com',		SYSDATETIME()),		
		(350,	NULL,	3,		0,		0,		N'DimOwnershipCAEGroup',					N'DimOwnershipCAEGroup',				N'Play to Pay Dim Ownership CAE Group Table',					N'PipelineWarehouse',	N'DimOwnershipCAEGroup',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(351,	NULL,	3,		0,		0,		N'FactOwnershipCAEGroup',					N'FactOwnershipCAEGroup',				N'Play to Pay Fact Ownership CAE Group Table',					N'PipelineWarehouse',	N'FactOwnershipCAEGroup',					N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(352,	NULL,	3,		0,		0,		N'DimDate',									N'dimDate',								N'Play to Pay Dim Date',										N'PipelineWarehouse',	N'DimDate',									N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(395,	NULL,	2,		0,		0,		N'ScrubFormat303Line00',					N'brcformat303line00',					N'Broadcast DataQuality Scrub Format303 Line00',				N'Format303',			N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(396,	NULL,	2,		0,		0,		N'ScrubFormat303Line10',					N'brcformat303line10',					N'Broadcast DataQuality Scrub Format303 Line10',				N'Format303',			N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(397,	NULL,	2,		0,		0,		N'ScrubFormat303Line20',					N'brcformat303line20',					N'Broadcast DataQuality Scrub Format303 Line20',				N'Format303',			N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(398,	NULL,	2,		0,		0,		N'ScrubFormat303Line99',					N'brcformat303line99',					N'Broadcast DataQuality Scrub Format303 Line99',				N'Format303',			N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(399,	NULL,	2,		0,		0,		N'ScrubFormat5Line00',						N'brcformat5line00',					N'Broadcast DataQuality Scrub Format5 Line00',					N'Format5',				N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(400,	NULL,	2,		0,		0,		N'ScrubFormat5Line10',						N'brcformat5line10',					N'Broadcast DataQuality Scrub Format5 Line10',					N'Format5',				N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(401,	NULL,	2,		0,		0,		N'ScrubFormat5Line20',						N'brcformat5line20',					N'Broadcast DataQuality Scrub Format5 Line20',					N'Format5',				N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(402,	NULL,	2,		0,		0,		N'ScrubFormat5Line99',						N'brcformat5line99',					N'Broadcast DataQuality Scrub Format5 Line99',					N'Format5',				N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(403,	NULL,	2,		0,		0,		N'ScrubFormat50Line00',						N'brcformat50line00',					N'Broadcast DataQuality Scrub Format50 Line00',					N'Format50',			N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(404,	NULL,	2,		0,		0,		N'ScrubFormat50Line10',						N'brcformat50line10',					N'Broadcast DataQuality Scrub Format50 Line10',					N'Format50',			N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(405,	NULL,	2,		0,		0,		N'ScrubFormat50Line20',						N'brcformat50line20',					N'Broadcast DataQuality Scrub Format50 Line20',					N'Format50',			N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(406,	NULL,	2,		0,		0,		N'ScrubFormat50Line99',						N'brcformat50line99',					N'Broadcast DataQuality Scrub Format50 Line99',					N'Format50',			N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(407,	NULL,	2,		0,		0,		N'ScrubFormat51Line00',						N'brcformat51line00',					N'Broadcast DataQuality Scrub Format51 Line00',					N'Format51',			N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(408,	NULL,	2,		0,		0,		N'ScrubFormat51Line10',						N'brcformat51line10',					N'Broadcast DataQuality Scrub Format51 Line10',					N'Format51',			N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(409,	NULL,	2,		0,		0,		N'ScrubFormat51Line20',						N'brcformat51line20',					N'Broadcast DataQuality Scrub Format51 Line20',					N'Format51',			N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(410,	NULL,	2,		0,		0,		N'ScrubFormat51Line99',						N'brcformat51line99',					N'Broadcast DataQuality Scrub Format51 Line99',					N'Format51',			N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(411,	NULL,	2,		0,		0,		N'ScrubFormat52Line00',						N'brcformat52line00',					N'Broadcast DataQuality Scrub Format52 Line00',					N'Format52',			N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(412,	NULL,	2,		0,		0,		N'ScrubFormat52Line10',						N'brcformat52line10',					N'Broadcast DataQuality Scrub Format52 Line10',					N'Format52',			N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(413,	NULL,	2,		0,		0,		N'ScrubFormat52Line20',						N'brcformat52line20',					N'Broadcast DataQuality Scrub Format52 Line20',					N'Format52',			N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(414,	NULL,	2,		0,		0,		N'ScrubFormat52Line99',						N'brcformat52line99',					N'Broadcast DataQuality Scrub Format52 Line99',					N'Format52',			N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(415,	NULL,	2,		0,		0,		N'ScrubFormat51aLine00',					N'brcformat51aline00',					N'Broadcast DataQuality Scrub Format51a Line00',				N'Format51a',			N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(416,	NULL,	2,		0,		0,		N'ScrubFormat51aLine10',					N'brcformat51aline10',					N'Broadcast DataQuality Scrub Format51a Line10',				N'Format51a',			N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(417,	NULL,	2,		0,		0,		N'ScrubFormat51aLine20',					N'brcformat51aline20',					N'Broadcast DataQuality Scrub Format51a Line20',				N'Format51a',			N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(418,	NULL,	2,		0,		0,		N'ScrubFormat51aLine99',					N'brcformat51aline99',					N'Broadcast DataQuality Scrub Format51a Line99',				N'Format51a',			N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(419,	NULL,	2,		0,		0,		N'ScrubFormatS1Line00',						N'brcformats1line00',					N'Broadcast DataQuality Scrub FormatS1 Line00',					N'FormatS1',			N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(420,	NULL,	2,		0,		0,		N'ScrubFormatS1Line10',						N'brcformats1line10',					N'Broadcast DataQuality Scrub FormatS1 Line10',					N'FormatS1',			N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(421,	NULL,	2,		0,		0,		N'ScrubFormatS1Line20',						N'brcformats1line20',					N'Broadcast DataQuality Scrub FormatS1 Line20',					N'FormatS1',			N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(422,	NULL,	2,		0,		0,		N'ScrubFormatS1Line99',						N'brcformats1line99',					N'Broadcast DataQuality Scrub FormatS1 Line99',					N'FormatS1',			N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(423,	NULL,	2,		0,		0,		N'ScrubFormatS2Line00',						N'brcformats2line00',					N'Broadcast DataQuality Scrub FormatS2 Line00',					N'FormatS2',			N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(424,	NULL,	2,		0,		0,		N'ScrubFormatS2Line10',						N'brcformats2line10',					N'Broadcast DataQuality Scrub FormatS2 Line10',					N'FormatS2',			N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(425,	NULL,	2,		0,		0,		N'ScrubFormatS2Line20',						N'brcformats2line20',					N'Broadcast DataQuality Scrub FormatS2 Line20',					N'FormatS2',			N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(426,	NULL,	2,		0,		0,		N'ScrubFormatS2Line99',						N'brcformats2line99',					N'Broadcast DataQuality Scrub FormatS2 Line99',					N'FormatS2',			N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(427,	NULL,	2,		0,		1,		N'ExtractData',								N'brcExtractData',						N'Broadcast DataQuality Extract Data',							N'Raw',					N'ExtractData',								N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(428,	NULL,	2,		0,		1,		N'MDSChannel',								N'brcMDSChannel',						N'Broadcast DataQuality MDS Channel',							N'MDS',					N'Channel',								    N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(429,	NULL,	2,		0,		1,		N'MDSChannelProductionType',				N'brcMDSChannelProductionType',			N'Broadcast DataQuality MDS ChannelProductionType',				N'MDS',					N'ChannelProductionType',					N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(430,	NULL,	2,		0,		1,		N'MDSFileSchedule',							N'brcMDSFileSchedule',					N'Broadcast DataQuality MDS FileSchedule',						N'MDS',					N'FileSchedule',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(431,	NULL,	2,		0,		0,		N'DataQualityScrubAvLine00',				N'brcDataQualityScrubAvLine00',			N'Broadcast DataQuality DataQuality Av Line00',					N'ScrubAv',					N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(432,	NULL,	2,		0,		0,		N'DataQualityScrubAvLine10',				N'brcDataQualityScrubAvLine10',			N'Broadcast DataQuality DataQuality Av Line10',					N'ScrubAv',					N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(433,	NULL,	2,		0,		0,		N'DataQualityScrubAvLine20',				N'brcDataQualityScrubAvLine20',			N'Broadcast DataQuality DataQuality Av Line20',					N'ScrubAv',					N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(434,	NULL,	2,		0,		0,		N'DataQualityScrubAvLine99',				N'brcDataQualityScrubAvLine99',			N'Broadcast DataQuality DataQuality Av Line99',					N'ScrubAv',					N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(435,	NULL,	2,		0,		0,		N'CleanAvLine00',							N'brcDataQualityCleanAvLine00',			N'Broadcast DataQuality Clean Av Line00',						N'Av',					N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(436,	NULL,	2,		0,		0,		N'CleanAvLine10',							N'brcDataQualityCleanAvLine10',			N'Broadcast DataQuality Clean Av Line10',						N'Av',					N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(437,	NULL,	2,		0,		0,		N'CleanAvLine20',							N'brcDataQualityCleanAvLine20',			N'Broadcast DataQuality Clean Av Line20',						N'Av',					N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(438,	NULL,	2,		0,		0,		N'CleanAvLine99',							N'brcDataQualityCleanAvLine99',			N'Broadcast DataQuality Clean Av Line99',						N'Av',					N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(439,	NULL,	2,		0,		0,		N'CleanAvFile',								N'brcDataQualityCleanAvFile',			N'Broadcast DataQuality Clean Av File',							N'Av',					N'File',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(440,	NULL,	2,		0,		0,		N'CleanRadioLine00',						N'brcDataQualityCleanRadioLine00',		N'Broadcast DataQuality Clean Radio Line00',					N'Radio',				N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(441,	NULL,	2,		0,		0,		N'CleanRadioLine10',						N'brcDataQualityCleanRadioLine10',		N'Broadcast DataQuality Clean Radio Line10',					N'Radio',				N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(442,	NULL,	2,		0,		0,		N'CleanRadioLine20',						N'brcDataQualityCleanRadioLine20',		N'Broadcast DataQuality Clean Radio Line20',					N'Radio',				N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(443,	NULL,	2,		0,		0,		N'CleanRadioLine99',						N'brcDataQualityCleanRadioLine99',		N'Broadcast DataQuality Clean Radio Line99',					N'Radio',				N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(444,	NULL,	2,		0,		0,		N'CleanRadioFile',							N'brcDataQualityCleanRadioFile',		N'Broadcast DataQuality Clean Radio File',						N'Radio',				N'File',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(445,	NULL,	2,		0,		0,		N'ConfigRuleThreshold',						N'brcDataQualityConfigRuleThreshold',	N'Broadcast DataQuality Config RuleThreshold',					N'Config',				N'RuleThreshold',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(446,	NULL,	2,		0,		0,		N'ConfigScoreThreshold',					N'brcDataQualityConfigScoreThreshold',	N'Broadcast DataQuality Config Score Threshold',				N'Config',				N'ScoreThreshold',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(447,	NULL,	2,		0,		0,		N'DataQualityScrubRadioLine00',				N'brcDataQualityScrubRadioLine00',		N'Broadcast DataQuality DataQuality Radio Line00',				N'ScrubRadio',				N'Line00',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(448,	NULL,	2,		0,		0,		N'DataQualityScrubRadioLine10',				N'brcDataQualityScrubRadioLine10',		N'Broadcast DataQuality DataQuality Radio Line10',				N'ScrubRadio',				N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(449,	NULL,	2,		0,		0,		N'DataQualityScrubRadioLine20',				N'brcDataQualityScrubRadioLine20',		N'Broadcast DataQuality DataQuality Radio Line20',				N'ScrubRadio',				N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(450,	NULL,	2,		0,		0,		N'DataQualityScrubRadioLine99',				N'brcDataQualityScrubRadioLine99',		N'Broadcast DataQuality DataQuality Radio Line99',				N'ScrubRadio',				N'Line99',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(451,	NULL,	2,		0,		0,		N'DataQualityCleanAvTabLine10',				N'brcDataQualityCleanAvTabLine10',		N'Broadcast DataQuality Clean Av Tab Line 10',					N'TabAv',					N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(452,	NULL,	2,		0,		0,		N'DataQualityCleanAvTabLine20',				N'brcDataQualityCleanAvTabLine20',		N'Broadcast DataQuality Clean Av Tab Line 20',					N'TabAv',					N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(453,	NULL,	2,		0,		0,		N'DataQualityCleanRadioTabLine10',			N'brcDataQualityCleanRadioTabLine10',	N'Broadcast DataQuality Clean Radio Tab Line 10',				N'TabRadio',				N'Line10',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(454,	NULL,	2,		0,		0,		N'DataQualityCleanRadioTabLine20',			N'brcDataQualityCleanRadioTabLine20',	N'Broadcast DataQuality Clean Radio Tab Line 20',				N'TabRadio',				N'Line20',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(455,	NULL,	2,		0,		0,		N'DataQualityDimChannel',					N'brcDataQualityDimChannel',			N'Broadcast DataQuality Dim Channel',							N'Dim',					N'Channel',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(456,	NULL,	2,		0,		0,		N'DataQualityDimDQProduction',				N'brcDataQualityDimDQProduction',		N'Broadcast DataQuality Dim DQProduction',						N'Dim',					N'DQProduction',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(457,	NULL,	2,		0,		0,		N'DataQualityDimDQProductionType',			N'brcDataQualityDimDQProductionType',	N'Broadcast DataQuality Dim DQProductionType',					N'Dim',					N'DQProductionType',						N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(458,	NULL,	2,		0,		0,		N'DataQualityDimDQRule',					N'brcDataQualityDimDQRule',				N'Broadcast DataQuality Dim DQRule',							N'Dim',					N'DQRule',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(459,	NULL,	2,		0,		0,		N'DataQualityDimFileLog',					N'brcDataQualityDimFileLog',			N'Broadcast DataQuality Dim FileLog',							N'Dim',					N'FileLog',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(460,	NULL,	2,		0,		0,		N'DataQualityDimScoreThreshold',			N'brcDataQualityDimScoreThreshold',		N'Broadcast DataQuality Dim ScoreThreshold',					N'Dim',					N'ScoreThreshold',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(461,	NULL,	2,		0,		0,		N'DataQualityDimScreen',					N'brcDataQualityDimScreen',				N'Broadcast DataQuality Dim Screen',							N'Dim',					N'Screen',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(462,	NULL,	2,		0,		0,		N'DataQualityFactDQFile',					N'brcDataQualityFactDQFile',			N'Broadcast DataQuality Fact DQFile',							N'Fact',				N'DQFile',									N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(463,	NULL,	2,		0,		0,		N'DataQualityFactDQOutcome',				N'brcDataQualityFactDQOutcome',			N'Broadcast DataQuality Fact DQOutcome',						N'Fact',				N'DQOutcome',								N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(464,	NULL,	2,		0,		0,		N'ReportingMissingDays',					N'brcReportingMissingDays',				N'Broadcast DataQuality Reporting Missing Days',				N'Reporting',			N'MissingDays',								N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(465,	NULL,	2,		0,		0,		N'ReportingProductionTypes',				N'brcReportingProductionTypes',			N'Broadcast DataQuality Reporting Missing Production Types',	N'Reporting',			N'MissingProductionTypes',					N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(466,	NULL,	2,		0,		0,		N'StatsAverageUsage',						N'brcStatsAverageUsage',				N'Broadcast DataQuality Stats Average Usage',					N'Stats',				N'AverageUsage',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(467,	NULL,	2,		0,		0,		N'StatsDQAggRowsBreakdown',					N'brcStatsDQAggRowsBreakdown',			N'Broadcast DataQuality Stats DQAggRowsBreakdown',				N'Stats',				N'DQAggRowsBreakdown',						N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(468,	NULL,	2,		0,		0,		N'StatsDQAggRulesBreakdown',				N'brcStatsDQAggRulesBreakdown',			N'Broadcast DataQuality Stats DQAggRulesBreakdown',				N'Stats',				N'DQAggRulesBreakdown',						N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(469,	NULL,	2,		0,		0,		N'StatsDQFileScore',						N'brcStatsDQFileScore',					N'Broadcast DataQuality Stats FileScore',						N'Stats',				N'DQFileScore',								N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(470,	NULL,	2,		0,		0,		N'StatsFileBreakDown',						N'brcStatsFileBreakDown',				N'Broadcast DataQuality Stats FileBreakDown',					N'Stats',				N'FileBreakDown',							N'vandana.bangera@prsformusic.com',	SYSDATETIME()),
		(500,	-1,		6,		1,		0,		N'ETL_DATA_FIX',							N'etldatafix',							N'ETLSystem Data File ETL_DATA_FIX',							N'staging',				N'ETL_DATA_FIX',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(501,	-1,		6,		1,		0,		N'ETL_ERROR_LOG',							N'etlerrorlog',							N'ETLSystem Data File ETL_ERROR_LOG',							N'staging',				N'ETL_ERROR_LOG',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(502,	-1,		6,		1,		0,		N'ETL_JOB_CTRL',							N'etljobctrl',							N'ETLSystem Data File ETL_JOB_CTRL',							N'staging',				N'ETL_JOB_CTRL',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(503,	-1,		6,		1,		0,		N'ETL_FOREIGN_FINANCIAL_SUMMARY',			N'etlforeignfinancialsummary',			N'ETLSystem Data File ETL_FOREIGN_FINANCIAL_SUMMARY',			N'staging',				N'ETL_FOREIGN_FINANCIAL_SUMMARY',			N'tim.firmin@prsformusic.com',		SYSDATETIME()),		
		(510,	-1,		6,		0,		0,		N'ETLDataFix',								N'dmt_etldatafix',						N'ETLSystem Datamart Table ETLDataFix',							N'datamart',			N'ETLDataFix',								N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(511,	-1,		6,		0,		0,		N'ETLErrorLog',								N'dmt_etlerrorlog',						N'ETLSystem Datamart Table ETLErrorLog',						N'datamart',			N'ETLErrorLog',								N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(512,	-1,		6,		0,		0,		N'ETLJobControl',							N'dmt_etljobctrl',						N'ETLSystem Datamart Table ETLJobControl',						N'datamart',			N'ETLJobControl',							N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(513,	-1,		6,		0,		0,		N'ETLForeignFinancialSummary',				N'dmt_etlforeignfinancialsummary',		N'ETLSystem Datamart Table ETLForeignFinancialSummary',			N'datamart',			N'ETLForeignFinancialSummary',				N'tim.firmin@prsformusic.com',		SYSDATETIME()),
		(514,	NULL,	3,		1,		0,		N'BatchControl',							N'prbibatchcontrol',					N'Oracle BATCH_CONTROL table',									N'PRBI_META',			N'BATCH_CONTROL',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(515,	NULL,	3,		1,		0,		N'UsageHeaders',							N'prbiusageheaders',					N'Oracle USAGE_HEADERS table',									N'PRBI_STAGINGTEMP',	N'USAGE_HEADERS',							N'emma.stewart@prsformusic.com',	SYSDATETIME()),
		(516,	NULL,	2,		0,		0,		N'ReportingMissingMDSEntities',				N'brcReportingMissingMDSEntities',		N'Broadcast DataQuality Reporting Missing Missing Entities',	N'Reporting',	        N'MissingMDSEntities',						N'senay.yilmaz@prsformusic.com',	SYSDATETIME()),
		(517,	NULL,	2,		0,		0,		N'BroadcastDataQualityFormat52r',		    N'brcdqformat52r',						N'Broadcast DataQuality Format52s',								N'BRCDataQuality',		N'BRC_DQ_Format52r',						N'senay.yilmaz@prsformusic.com',	SYSDATETIME()),
		(518,	-1,		8,		1,		0,		N'SASPayments',								N'saspayments',							N'SAS Payments table',											N'SAS',					N'SAS_PAYMENTS',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(519,	-1,		8,		1,		0,		N'SASAccountSummaries',						N'sasaccountsummaries',					N'SAS Account Summaries table',									N'SAS',					N'SAS_ACCOUNT_SUMMARIES',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(520,	-1,		8,		1,		0,		N'SASCommissionInvoice',					N'sascommissioninvoice',				N'SAS Commission Invoice table',								N'SAS',					N'SAS_COMMISSION_INVOICE',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(521,	-1,		8,		1,		0,		N'SASEarnings',								N'sasearnings',							N'SAS Earnings table',											N'SAS',					N'SAS_EARNINGS',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(522,	-1,		8,		1,		0,		N'SASGeneralAdjDetails',					N'sasgeneraladjdetails',				N'SAS General Adj Details table',								N'SAS',					N'SAS_GENERAL_ADJ_DETAILS',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(523,	-1,		8,		1,		0,		N'SASStatementSocieties',					N'sasstatementsocieties',				N'SAS Statement Societies table',								N'SAS',					N'SAS_STATEMENT_SOCIETIES',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(524,	-1,		8,		1,		0,		N'SASStatements',							N'sasstatements',						N'SAS Statements table',										N'SAS',					N'SAS_STATEMENTS',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(525,	-1,		8,		1,		0,		N'SASVATInvoices',							N'sasvatinvoices',						N'SAS VAT Invoices table',										N'SAS',					N'SAS_VAT_INVOICES',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(526,	-1,		8,		1,		0,		N'SASNoticeOfPayments',						N'sasnoticeofpayments',					N'SAS Notice Of Payments table',								N'SAS',					N'SAS_NOTICE_OF_PAYMENTS',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(530,	-1,		11,		1,		0,		N'ICEPacketItem',							N'ICE_PACKET_ITEM',						N'ICE Packet Item File',										N'ICE',					N'ICE_PACKET_ITEM',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(531,	-1,		11,		1,		0,		N'ICEWorkUse',								N'ICE_WORK_USE',						N'ICE Work Use file',											N'ICE',					N'ICE_WORK_USE',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(532,	-1,		11,		1,		0,		N'ICEConsumerDeal',							N'ICE_CONSUMERD_EAL',					N'ICE Consumer Deal File',										N'ICE',					N'ICE_CONSUMER_DEAL',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(533,	-1,		11,		1,		0,		N'ICEIptyFreeze',							N'ICE_IPTY_FREEZE',						N'ICE IPTY freeze file',										N'ICE',					N'ICE_IPTY_FREEZE',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
	  --[EI],	[PETI],	[AI],	[IS],	[HMS],	[Name],										[Code],									[Description],													[Schema],				[Table],									[CreatedBy]							[CreatedDate]
		(600,	NULL,	12,		1,		0,		N'AdjustmentReason',						N'DM_ADJUSTMENT_REASON',				N'Oracle ADJUSTMENT_REASON table',								N'DMOWN',				N'DM_ADJUSTMENT_REASON',					N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(601,	NULL,	12,		1,		0,		N'BroadcastRegion',							N'DM_BROADCAST_REGION',					N'Oracle BROADCAST_REGION table',								N'DMOWN',				N'DM_BROADCAST_REGION',						N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(602,	NULL,	12,		1,		0,		N'Cae',										N'DM_CAE',								N'Oracle CAE table',											N'DMOWN',				N'DM_CAE',									N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(603,	NULL,	12,		1,		0,		N'CashingOutGroup',							N'DM_CASHING_OUT_GROUP',				N'Oracle CASHING_OUT_GROUP table',								N'DMOWN',				N'DM_CASHING_OUT_GROUP',					N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(604,	NULL,	12,		1,		0,		N'Currency',								N'DM_CURRENCY',							N'Oracle CURRENCY table',										N'DMOWN',				N'DM_CURRENCY',								N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(605,	NULL,	12,		1,		1,		N'DigitalTransactions',						N'DM_DIGITALTRANSACTIONS',				N'Oracle DIGITAL_TRANSACTIONS table',							N'DMOWN',				N'DM_DIGITAL_TRANSACTIONS',					N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(606,	NULL,	12,		1,		0,		N'Distribution',							N'DM_DISTRIBUTION',						N'Oracle DISTRIBUTION table',									N'DMOWN',				N'DM_DISTRIBUTION',							N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(607,	NULL,	12,		1,		0,		N'Invoices',								N'DM_INVOICES',							N'Oracle INVOICES table',										N'DMOWN',				N'DM_INVOICES',								N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(608,	NULL,	12,		1,		0,		N'LicensingBodies',							N'DM_LICENSING_BODIES',					N'Oracle LICENSING_BODIES table',								N'DMOWN',				N'DM_LICENSING_BODIES',						N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(609,	NULL,	12,		1,		0,		N'MemberDistributionSumm',					N'DM_MEMBER_DISTRIBUTION_SUMM',			N'Oracle MEMBER_DISTRIBUTION_SUMM table',						N'DMOWN',				N'DM_MEMBER_DISTRIBUTION_SUMM',				N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(610,	NULL,	12,		1,		0,		N'MembershipType',							N'DM_MEMBERSHIP_TYPE',					N'Oracle MEMBERSHIP_TYPE table',								N'DMOWN',				N'DM_MEMBERSHIP_TYPE',						N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(611,	NULL,	12,		1,		0,		N'Performance',								N'DM_PERFORMANCE',						N'Oracle PERFORMANCE table',									N'DMOWN',				N'DM_PERFORMANCE',							N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(612,	NULL,	12,		1,		0,		N'ProductTypes',							N'DM_PRODUCT_TYPES',					N'Oracle PRODUCT_TYPES table',									N'DMOWN',				N'DM_PRODUCT_TYPES',						N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(613,	NULL,	12,		1,		0,		N'PsMembersInDist',							N'DM_PS_MEMBERS_IN_DIST',				N'Oracle PS_MEMBERS_IN_DIST table',								N'DMOWN',				N'DM_PS_MEMBERS_IN_DIST',					N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(614,	NULL,	12,		1,		0,		N'RepertoirePosting',						N'DM_REPERTOIRE_POSTING',				N'Oracle REPERTOIRE_POSTING table',								N'DMOWN',				N'DM_REPERTOIRE_POSTING',					N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(615,	NULL,	12,		1,		0,		N'RoyaltyLineTransfer',						N'DM_ROYALTY_LINE_TRANSFER',			N'Oracle ROYALTY_LINE_TRANSFER table',							N'DMOWN',				N'DM_ROYALTY_LINE_TRANSFER',				N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(616,	NULL,	12,		1,		1,		N'RoyaltyTransaction',						N'DM_ROYALTY_TRANSACTION',				N'Oracle ROYALTY_TRANSACTION table',							N'DMOWN',				N'DM_ROYALTY_TRANSACTION',					N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(617,	NULL,	12,		1,		0,		N'ServiceTypes',							N'DM_SERVICE_TYPES',					N'Oracle SERVICE_TYPES table',									N'DMOWN',				N'DM_SERVICE_TYPES',						N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(618,	NULL,	12,		1,		0,		N'Society',									N'DM_SOCIETY',							N'Oracle SOCIETY table',										N'DMOWN',				N'DM_SOCIETY',								N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(619,	NULL,	12,		1,		0,		N'UsageCategories',							N'DM_USAGE_CATEGORIES',					N'Oracle USAGE_CATEGORIES table',								N'DMOWN',				N'DM_USAGE_CATEGORIES',						N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(620,	NULL,	12,		1,		0,		N'UsageGroup',								N'DM_USAGE_GROUP',						N'Oracle USAGE_GROUP table',									N'DMOWN',				N'DM_USAGE_GROUP',							N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(621,	NULL,	12,		1,		0,		N'UsageGroupSumm',							N'DM_USAGE_GROUP_SUMM',					N'Oracle USAGE_GROUP_SUMM table',								N'DMOWN',				N'DM_USAGE_GROUP_SUMM',						N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(622,	NULL,	12,		1,		0,		N'UsageGroupType',							N'DM_USAGE_GROUP_TYPE',					N'Oracle USAGE_GROUP_TYPE table',								N'DMOWN',				N'DM_USAGE_GROUP_TYPE',						N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(623,	NULL,	12,		1,		0,		N'Country',									N'MEM_COUNTRY',							N'Oracle COUNTRY table',										N'MEMOWN',				N'MEM_COUNTRY',								N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),
		(624,	NULL,	12,		1,		0,		N'Membership',								N'MEM_MEMBERSHIP',						N'Oracle MEMBERSHIP table',										N'MEMOWN',				N'MEM_MEMBERSHIP',							N'piotr.starczynski@prsformusic.com',  SYSDATETIME()),	

		(625,	NULL,	2,   	0,	    0,      N'ScrubFormat52rLine00',                 	N'brcformat52rline00',                	N'Broadcast DataQuality Scrub Format52r Line00',      	        N'Format52r',      	    N'Line00',                                  N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),	
		(626,	NULL,	2,   	0,	    0,      N'ScrubFormat52rLine10',                 	N'brcformat52rline10',                	N'Broadcast DataQuality Scrub Format52r Line10',      	        N'Format52r',      	    N'Line10',                                  N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),	
		(627,	NULL,	2,   	0,	    0,      N'ScrubFormat52rLine20',                 	N'brcformat52rline20',                	N'Broadcast DataQuality Scrub Format52r Line20',      	        N'Format52r',      	    N'Line20',                                  N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(628,	NULL,	2,   	0,	    0,      N'ScrubFormat52rLine99',                 	N'brcformat52rline99',                	N'Broadcast DataQuality Scrub Format52r Line99',      	        N'Format52r',      	    N'Line99',                                  N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),

		(629,	NULL,	10,   	0,	    0,      N'Stage.Accounts',                       	N'Stage.Accounts',                  	N'Dotmailer Stage Accounts',      	                            N'Stage',        	    N'Accounts',                                N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(630,	NULL,	10,   	0,	    0,      N'Stage.APICall',                       	N'Stage.APICall',                   	N'Dotmailer Stage APICall',      	                            N'Stage',        	    N'APICall',                                 N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(631,	NULL,	10,   	0,	    0,      N'Stage.APICallWeekly',                     N'Stage.APICallWeekly',                 N'Dotmailer Stage APICallWeekly',      	                        N'Stage',        	    N'APICallWeekly',                           N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(632,	NULL,	10,   	0,	    0,      N'Scrub.Accounts',                          N'Scrub.Accounts',                      N'Dotmailer Scrub   Accounts',      	                        N'Scrub',        	    N'Accounts',                                N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(633,	NULL,	10,   	0,	    0,      N'Scrub.Campaigns',                         N'Scrub.Campaigns',                     N'Dotmailer Scrub   Campaigns',      	                        N'Scrub',        	    N'Campaigns',                               N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(634,	NULL,	10,   	0,	    0,      N'Scrub.CampaignsHardBouncers',             N'Scrub.CampaignsHardBouncers',         N'Dotmailer Scrub   CampaignsHardBouncers',                     N'Scrub',        	    N'CampaignsHardBouncers',                   N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(635,	NULL,	10,   	0,	    0,      N'Scrub.CampaignsWithActivity',             N'Scrub.CampaignsWithActivity',         N'Dotmailer Scrub   CampaignsWithActivity',                     N'Scrub',        	    N'CampaignsWithActivity',                   N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(636,	NULL,	10,   	0,	    0,      N'Scrub.CampaignsOpenSinceDate',            N'Scrub.CampaignsOpenSinceDate',        N'Dotmailer Scrub   CampaignsOpenSinceDate',                    N'Scrub',        	    N'CampaignsOpenSinceDate',                  N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(637,	NULL,	10,   	0,	    0,      N'Scrub.CampaignsClicksSinceDate',          N'Scrub.CampaignsClicksSinceDate',      N'Dotmailer Scrub   CampaignsClicksSinceDate',                  N'Scrub',        	    N'CampaignsClicksSinceDate',                N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(638,	NULL,	10,   	0,	    0,      N'Scrub.CampaignActivitySinceDate',         N'Scrub.CampaignActivitySinceDate',     N'Dotmailer Scrub   CampaignActivitySinceDate',                 N'Scrub',        	    N'CampaignActivitySinceDate',               N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(639,	NULL,	10,   	0,	    0,      N'Scrub.CampaignSummary',                   N'Scrub.CampaignSummary',               N'Dotmailer Scrub   CampaignSummary',                           N'Scrub',        	    N'CampaignSummary',                         N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(640,	NULL,	10,   	0,	    0,      N'Scrub.Contacts',                          N'Scrub.Contacts',                      N'Dotmailer Scrub   Contacts',                                  N'Scrub',        	    N'Contacts',                                N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(641,	NULL,	10,   	0,	    0,      N'Scrub.AddressBooks',                      N'Scrub.AddressBooks',                  N'Dotmailer Scrub   AddressBooks',                              N'Scrub',        	    N'AddressBooks',                            N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(642,	NULL,	10,   	0,	    0,      N'Scrub.ContactsFromAddressBooks',          N'Scrub.ContactsFromAddressBooks',      N'Dotmailer Scrub   ContactsFromAddressBooks',                  N'Scrub',        	    N'ContactsFromAddressBooks',                N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		--BI Turquoise BI System Entity Block 700-720
		(700,	NULL,	9,   	0,	    0,      N'BITstaging.StagedDistribution',           N'BITstaging.StagedDistribution',       N'BITurquoise Distribution File Moved Landing to Staging',      N'BITstaging',        	N'BITstaging.StagedDistribution',           N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(701,	NULL,	9,   	0,	    0,      N'BITstaging.StagedInvoice',				N'BITstaging.StagedInvoice',		    N'BITurquoise Invoice File Moved Landing to Staging',			N'BITstaging',        	N'BITstaging.StagedInvoice',                N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(702,	NULL,	9,   	0,	    0,      N'BITstaging.StagedTrueUp',					N'BITstaging.StagedTrueUp',				N'BITurquoise True-Up File Moved Landing to Staging',			N'BITstaging',        	N'BITstaging.StagedTrueUp',					N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(703,	NULL,	9,   	0,	    0,      N'BITstaging.StagedVAT',					N'BITstaging.StagedVAT',				N'BITurquoise VAT File Moved Landing to Staging',				N'BITstaging',        	N'BITstaging.StagedVAT',					N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(704,	NULL,	9,   	0,	    0,      N'BITstaging.StagedCash',					N'BITstaging.StagedCash',				N'BITurquoise File Staged Only Not Processed',					N'BITstaging',        	N'BITstaging.StagedCash',					N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(705,	NULL,	9,   	0,	    0,      N'BITValidateFiles',						N'BITValidateFiles',					N'BITurquoise BITValidateFiles',								N'BITtransform',        N'BITstaging.StagedXXX',					N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(706,	NULL,	9,   	0,	    0,      N'BITProcessFiles',							N'BITProcessFiles',						N'BITurquoise BITProcessFiles',									N'BITtransform',        N'BITtransform.StagedCash',					N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(707,	NULL,	9,   	0,	    0,      N'BITExportFiles',							N'BITExportFiles',						N'BITurquoise BITExportFiles',									N'BITDatamart',        	N'BITstaging.StagedCash',					N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(708,	NULL,	9,   	0,	    0,      N'BITextract.linkline',						N'BITextract.linkline',					N'BITurquoise BITextract.linkline',								N'BITDatamart',        	N'BITextract.linkline',						N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(709,	NULL,	9,   	0,	    0,      N'CODA.prs_linkline',						N'CODA.prs_linkline',					N'BITurquoise BI Export CODA linkhead',							N'BITDatamart',        	N'CODA.prs_linkline',						N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(710,	NULL,	9,   	0,	    0,      N'BITreporting.BITMigrated',				N'BITreporting.BITMigrated',			N'BITurquoise BITreporting.BITMigrated',						N'BITDatamart',        	N'BITreporting.BITMigrated',				N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(711,	NULL,	9,   	0,	    0,      N'BITreporting.BITCashData',				N'BITreporting.BITCashData',			N'BITurquoise BITreporting.BITCashData',						N'BITDatamart',        	N'BITreporting.BITCashData',				N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(712,	NULL,	9,   	0,	    0,      N'BITreporting.BITInvoiceData',				N'BITreporting.BITInvoiceData',			N'BITurquoise BITreporting.BITInvoiceData',						N'BITDatamart',        	N'BITreporting.BITInvoiceData',				N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		(713,	NULL,	9,   	0,	    0,      N'BITreporting.BITDistributionData',		N'BITreporting.BITDistributionData',	N'BITurquoise BITreporting.BITDistributionData',				N'BITDatamart',        	N'BITreporting.BITDistributionData',		N'tim.firmin@prsformusic.com',  SYSDATETIME()),
		-- SAS Datafixes

		(720,	-1,		8,		1,		0,		N'SASStatementChanges',						N'sasstatementchanges',					N'SAS Statement Changes table',									N'SAS',					N'SAS_STATEMENT_CHANGES',					N'vandana.bangera@prsformusic.com',	SYSDATETIME()),

		-- Online Migration 
		--[EI],	[PETI],	[AI],	[IS],	[HMS],	[Name],										[Code],									[Description],													[Schema],				[Table],									[CreatedBy]								[CreatedDate]
		(721,	NULL,	5,		1,		0,		N'Default',									N'NA',									N'NA',															N'N/A',					N'N/A',										N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(722,	NULL,	5,		1,		0,		N'OrcCreationComponent',					N'OrcCreationComponent',				N'OracleCreationComponent',										N'Oracle',				N'CreationComponent',						N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(723,	NULL,	5,		1,		0,		N'OrcUsageHeader',							N'OrcUsageHeader',						N'OracleUsageHeader',											N'Oracle',				N'UsageHeader',								N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(724,	NULL,	5,		1,		0,		N'OrcUsageComponent',						N'OrcUsageComponent',					N'OracleUsageComponent',										N'Oracle',				N'UsageComponent',							N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(725,	NULL,	5,		1,		0,		N'OrcInvoiceUsageComponents',				N'OrcInvoiceUsageComponents',			N'OracleInvoiceUsageComponents',								N'Oracle',				N'InvoiceUsageComponents',					N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(726,	NULL,	5,		1,		0,		N'OrcWorkContributorBridge',				N'OrcWorkContributorBridge',			N'OracleWorkContributorBridge',									N'Oracle',				N'WorkContributorBridge',					N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(727,	NULL,	5,		1,		0,		N'OrcContributor',							N'OrcContributor',						N'OracleContributor',											N'Oracle',				N'Contributor',								N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(728,	NULL,	5,		1,		0,		N'OrcAudioVisualContributor',				N'OrcAudioVisualContributor',			N'OracleAudioVisualContributor',								N'Oracle',				N'AudioVisualContributor',					N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(729,	NULL,	5,		1,		0,		N'OrcUsageRoyaltyTransactions',				N'OrcUsageRoyaltyTransactions',			N'OracleUsageRoyaltyTransactions',								N'Oracle',				N'UsageRoyaltyTransactions',				N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(730,	NULL,	5,		1,		0,		N'InvoiceRequestSalesRevenues',				N'InvoiceRequestSalesRevenues',			N'OracleInvoiceRequestSalesRevenues',							N'Oracle',				N'InvoiceRequestSalesRevenues',				N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(731,	NULL,	5,		1,		0,		N'InvoiceRequestRHGRoyalties',				N'InvoiceRequestRHGRoyalties',			N'OracleInvoiceRequestRHGRoyalties',							N'Oracle',				N'InvoiceRequestRHGRoyalties',				N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(732,	NULL,	5,		1,		0,		N'InvoiceRequestSummaries',					N'InvoiceRequestSummaries',				N'OracleInvoiceRequestSummaries',								N'Oracle',				N'InvoiceRequestSummaries',					N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(733,	NULL,	5,		1,		0,		N'Broadcasters',							N'Broadcasters',						N'OracleBroadcasters',											N'Oracle',				N'Broadcasters',							N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(734,	NULL,	5,		1,		0,		N'ElementaryTerritories',					N'ElementaryTerritories',				N'OracleElementaryTerritories',									N'Oracle',				N'ElementaryTerritories',					N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(735,	NULL,	5,		1,		0,		N'FilePaperLogs',							N'FilePaperLogs',						N'OracleFilePaperLogs',											N'Oracle',				N'FilePaperLogs',							N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(736,	NULL,	5,		1,		0,		N'FilePeriods',								N'FilePeriods',							N'OracleFilePeriods',											N'Oracle',				N'FilePeriods',								N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(737,	NULL,	5,		1,		0,		N'FileUsageByTerritory',					N'FileUsageByTerritory',				N'OracleFileUsageByTerritory',									N'Oracle',				N'FileUsageByTerritory',					N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(738,	NULL,	5,		1,		0,		N'Invoices',								N'Invoices',							N'OracleInvoices',												N'Oracle',				N'Invoices',								N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(739,	NULL,	5,		1,		0,		N'LicensedFiles',							N'LicensedFiles',						N'OracleLicensedFiles',											N'Oracle',				N'LicensedFiles',							N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(740,	NULL,	5,		1,		0,		N'Licences',								N'Licences',							N'OracleLicences',												N'Oracle',				N'Licences',								N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(741,	NULL,	5,		1,		0,		N'ReceivedFileLogs',						N'ReceivedFileLogs',					N'OracleReceivedFileLogs',										N'Oracle',				N'ReceivedFileLogs',						N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(742,	NULL,	5,		1,		0,		N'Recordings',								N'Recordings',							N'OracleRecordings',											N'Oracle',				N'Recordings',								N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(743,	NULL,	5,		1,		0,		N'RightHolderRepGroups',					N'RightHolderRepGroups',				N'OracleRightHolderRepGroups',									N'Oracle',				N'RightHolderRepGroups',					N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(744,	NULL,	5,		1,		0,		N'RightHolderGroups',						N'RightHolderGroups',					N'OracleRightHolderGroups',										N'Oracle',				N'RightHolderGroups',						N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(745,	NULL,	5,		1,		0,		N'ServiceTypes',							N'ServiceTypes',						N'OracleServiceTypes',											N'Oracle',				N'ServiceTypes',							N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(746,	NULL,	5,		1,		0,		N'OrcWorks',								N'OrcWorks',							N'OracleWorks',													N'Oracle',				N'Works',									N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(747,	NULL,	5,		1,		0,		N'RightsHolderGroupParameters',				N'RightsHolderGroupParameters',			N'OracleRightsHolderGroupParameters',							N'Oracle',				N'RightsHolderGroupParameters',				N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(748,	NULL,	5,		1,		0,		N'LicensingBodies',							N'LicensingBodies',						N'OracleLicensingBodies',										N'Oracle',				N'LicensingBodies',							N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(749,	NULL,	5,		1,		0,		N'LIBORHGBridge',							N'LIBORHGBridge',						N'OracleLIBORHGBridge',											N'Oracle',				N'LIBORHGBridge',							N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(750,	NULL,	5,		1,		0,		N'Mandates',								N'Mandates',							N'OracleMandates',												N'Oracle',				N'Mandates',								N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(751,	NULL,	5,		1,		0,		N'UsageDistributionCodes',					N'UsageDistributionCodes',				N'OracleUsageDistributionCodes',								N'Oracle',				N'UsageDistributionCodes',					N'vandana.bangera@prsformusic.com',		SYSDATETIME()),
		(752,	NULL,	5,		1,		0,		N'UsageDistributionGroups',					N'UsageDistributionGroups',				N'OracleUsageDistributionGroups',								N'Oracle',				N'UsageDistributionGroups',					N'vandana.bangera@prsformusic.com',		SYSDATETIME()),


		-- SAS DataFixes
		(753,	NULL,	8,		0,		0,		N'AdjustmentLine',							N'AdjustmentLine',						N'Online Statements Adjustment Line',							N'Warehouse',			N'AdjustmentLine',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(755,	NULL,	8,		0,		0,		N'CommissionInvoiceLine',					N'CommInvoiceLine',						N'Online Statements Comm Invoice Line',							N'Warehouse',			N'CommissionInvoiceLine',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		 										 
		(756,	NULL,	8,		0,		0,		N'GeneralRoyaltyLine',						N'GeneralRoyaltyLine',					N'General Loyalty Line',										N'Warehouse',			N'GeneralRoyaltyLine',						N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(757,	NULL,	8,		0,		0,		N'NopEarningLine',							N'NopEarningLine',						N'Nop Earning Line',											N'Warehouse',			N'NopEarningLine',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(759,	NULL,	8,		0,		0,		N'NopPaymentLine',							N'NopPaymentLine',						N'Nop Payment Line',											N'Warehouse',			N'NopPaymentLine',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(761,	NULL,	8,		0,		0,		N'OnlineStatement',							N'OnlineStatement',						N'Online Statement',											N'Warehouse',			N'OnlineStatement',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(762,	NULL,	8,		0,		0,		N'SourceStatement',							N'SourceStatement',						N'Source Statement',											N'Warehouse',			N'SourceStatement',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
												
		(763,	NULL,	8,		0,		0,		N'UsageGroupRoyaltyLine',					N'UsageGrpRoyLine',						N'Usage Group Royalty Line',									N'Warehouse',			N'UsgaeGroupRoyaltyLine',					N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		(765,	NULL,	8,		0,		0,		N'VATInvoiceLine',							N'VATInvoiceLine',						N'VATInvoiceLine',												N'Warehouse',			N'VATInvoiceLine',							N'Emma.Stewart@prsformusic.com',	SYSDATETIME()),
		
		--[EI],	[PETI],	[AI],	[IS],	[HMS],	[Name],										[Code],									[Description],													[Schema],				[Table],									[CreatedBy]							[CreatedDate]
		(766,	NULL,	10,   	0,	    0,      N'FactCampaignSummary',                     N'FactCampaignSummary',                 N'Dotmailer Scrub   FactCampaignSummary',                       N'DotM',        	    N'FactCampaignSummary',                     N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(767,	NULL,	10,   	0,	    0,      N'FactCampaignActivities',                  N'FactCampaignActivities',              N'Dotmailer Scrub   FactCampaignActivities',                    N'DotM',        	    N'FactCampaignActivities',                  N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(768,	NULL,	10,   	0,	    0,      N'FactCampaignActivityDetails',             N'FactCampaignActivityDetails',         N'Dotmailer Scrub   FactCampaignActivityDetails',               N'DotM',     	        N'FactCampaignActivityDetails',             N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(769,	NULL,	10,   	0,	    0,      N'Dimentions',                              N'Dimentions',                          N'Dotmailer Scrub   Dimentions',                                N'DotM',        	    N'Dimentions',                              N'senay.yilmaz@prsformusic.com',  SYSDATETIME()),
		(770,	NULL,	10,   	0,	    0,      N'Stage.MemberDetails',                     N'Stage.MemberDetails',                 N'Dotmailer Stage   MemberDetails',                             N'Stage',        	    N'MemberDetails',                           N'senay.yilmaz@prsformusic.com',  SYSDATETIME())
	) AS Src
	(
		 EntityTypeId
		,ParentEntityTypeId
		,ApplicationId
		,IsSourceEntity
		,[HasMultipleSourceFile]
		,Name
		,Code
		,[Description]
		,[Schema]
		,[Table]
		,[CreatedBy]
        ,[CreatedDate]
	)
	ON Tgt.EntityTypeId = Src.EntityTypeId

-- Update matched rows
WHEN MATCHED THEN
	UPDATE
	SET
		[ApplicationId]			= Src.[ApplicationId],
		[IsSourceEntity]	    = Src.[IsSourceEntity],
		[HasMultipleSourceFile]	= Src.[HasMultipleSourceFile],
		[Name]					= Src.[Name],
		[Code]					= Src.[Code],
		[ParentEntityTypeId]	= Src.[ParentEntityTypeId],
		[Description]			= Src.[Description],
		[Schema]				= Src.[Schema],
		[Table]					= Src.[Table],
		[CreatedBy]				= Src.[CreatedBy],
        [CreatedDate]			= Src.[CreatedDate]

-- Insert new rows
WHEN NOT MATCHED BY TARGET THEN
	INSERT
		(
			[EntityTypeId],
			[ApplicationId],
			[IsSourceEntity],
			[HasMultipleSourceFile],
			[Name],				
			[Code],				
			[ParentEntityTypeId],
			[Description],		
			[Schema],			
			[Table],				
			[CreatedBy],			
			[CreatedDate]		
		)
	VALUES
		(
			Src.[EntityTypeId],
			Src.[ApplicationId],
			Src.[IsSourceEntity],
			Src.[HasMultipleSourceFile],
			Src.[Name],
			Src.[Code],
			src.[ParentEntityTypeId],
			src.[Description],
			src.[Schema],
			src.[Table],
			src.[CreatedBy],			
			src.[CreatedDate]
		)

--  Delete rows that are in the target but not the source
WHEN NOT MATCHED BY SOURCE THEN
	DELETE;
GO
SET IDENTITY_INSERT [Control].[EntityType] OFF;


