CREATE TABLE  [Staging].[Broadcasters](
	[TP_SURR_ID]                     decimal(12,0) NOT NULL,
	[DN_TP_NAME]                     [varchar](60) NOT NULL,
	[STATION_ID]                     [varchar](6)  NOT NULL,
	[GC_TRANS_TYPE_TABLE]            [varchar](5)  NULL,
	[GC_TRANS_TYPE_CODE]             [varchar](5)  NULL,
	[DURATION_THRESHOLD]             decimal(6,0)  NULL,
	[SKIP_AUTO_MATCH_YN]             [varchar](1)  NOT NULL,
	[SKIP_LEARNED_MATCH_YN]          [varchar](1)  NOT NULL,
	[SKIP_TUNECODE_MATCH_YN]         [varchar](1)  NOT NULL,
	[EXTERNAL_STATION_ID]            [varchar](20) NULL,
	[REPORTS_SPLIT_USAGES]           [varchar](1)  NOT NULL,
	[CINEMA_FILM_USAGE_YN]           [varchar](1)  NOT NULL,
	[MTC_CODE]                       [varchar](5)  NULL,
	[TP_ROLLUP_SURR_ID]              decimal(12,0) NULL,
	[ALLUK_CUSTOMER_ACCOUNT_NO]      [varchar](20) NULL,
	[CELAS_CUSTOMER_ACCOUNT_NO]      [varchar](20) NULL,
	[ELT_CODE]                       [varchar](5)  NULL,
	[OUTSTANDING_CASE_THRESHOLD]     decimal(7,3)  NULL,
	[JOINT_PROCESSING_DATE]          datetime      NULL,
	[JOINT_PROCESSING_CATEGORY]      [varchar](5)  NULL,
	[MEMBER_MATCH_Y]                 [varchar](1)  NULL,
	[WLMM_RADIO_THRESHOLD_APPLIES_Y] [varchar](1)  NULL,
	[CODA_TAX_CODE]                  [varchar](12) NULL,
	[DOM_SURR_ID]                    decimal(12,0) NULL,
	[UPDATE_TRACK_CONTRIBUTORS_Y]    [varchar](1)  NULL,
	[UPDATE_TRACK_TITLE_Y]           [varchar](1)  NULL,
	[UPDATE_TRACK_IDS_Y]             [varchar](1)  NULL,
	[WEBSITE_GROUP]                  [varchar](60) NULL,
	[WEBSITE_EXCLUDE_Y]              [varchar](1)  NULL,
	LoadID                           int           NOT NULL,
	SysStartTime                     datetime      NOT NULL,
	SysEndTime                       datetime      NULL
) ON [PRIMARY]

GO