CREATE TABLE [SSIS].[executions] (
    [execution_id]                 BIGINT             IDENTITY (1, 1) NOT NULL,
    [folder_name]                  [sysname]          NOT NULL,
    [project_name]                 [sysname]          NOT NULL,
    [package_name]                 NVARCHAR (260)     NOT NULL,
    [reference_id]                 BIGINT             NULL,
    [reference_type]               CHAR (1)           NULL,
    [environment_folder_name]      NVARCHAR (128)     NULL,
    [environment_name]             NVARCHAR (128)     NULL,
    [project_lsn]                  BIGINT             NULL,
    [executed_as_sid]              VARBINARY (85)     NOT NULL,
    [executed_as_name]             NVARCHAR (128)     NOT NULL,
    [use32bitruntime]              BIT                NOT NULL,
    [operation_type]               SMALLINT           NOT NULL,
    [created_time]                 DATETIMEOFFSET (7) NULL,
    [object_type]                  SMALLINT           NULL,
    [object_id]                    BIGINT             NULL,
    [status]                       INT                NULL,
    [start_time]                   DATETIMEOFFSET (7) NULL,
    [end_time]                     DATETIMEOFFSET (7) NULL,
    [caller_sid]                   VARBINARY (85)     NULL,
    [caller_name]                  [sysname]          NOT NULL,
    [process_id]                   INT                NULL,
    [stopped_by_sid]               VARBINARY (85)     NULL,
    [stopped_by_name]              NVARCHAR (128)     NULL,
    [dump_id]                      UNIQUEIDENTIFIER   NULL,
    [server_name]                  NVARCHAR (128)     NULL,
    [machine_name]                 NVARCHAR (128)     NULL,
    [total_physical_memory_kb]     BIGINT             NULL,
    [available_physical_memory_kb] BIGINT             NULL,
    [total_page_file_kb]           BIGINT             NULL,
    [available_page_file_kb]       BIGINT             NULL,
    [cpu_count]                    INT                NULL
);

