CREATE TABLE [Control].[Notification] (
    [NotificationId]            INT            IDENTITY (1, 1) NOT NULL,
    [NotificationTypeId]        INT            NULL,
    [ExecutionInstanceGuid]     NVARCHAR (100) NULL,
    [LoadId]                    INT            NULL,
    [ShortDescription]          NVARCHAR (250) NULL,
    [Description]               NVARCHAR (MAX) NULL,
    [ErrorCode]                 NVARCHAR (128) NULL,
    [VerboseDescription]        NVARCHAR (MAX) NULL,
    [NotificationSeverityId]    INT            NULL,
    [NotificationStatusId]      INT            NULL,
    [NotificationProcessTypeId] INT            NULL,
    [LoadStatusType]            VARCHAR (20)   NULL,
    [FeedName]                  NVARCHAR (256) NULL,
    [Stage]                     NVARCHAR (200) NULL,
    [EntityName]                VARCHAR (50)   NULL,
    [SourceFileName]            NVARCHAR (256) NULL,
    [SuccessRows]               INT            NULL,
    [FailedRows]                INT            NULL,
    [BadRows]                   INT            NULL,
    [FeedStartTime]             DATETIME       NULL,
    [TimeOfCompletion]          DATETIME       NULL,
    [CreatedBy]                 [sysname]      DEFAULT (suser_sname()) NOT NULL,
    [RetryOnFailure]            INT            NULL,
    CONSTRAINT [pkcNotification] PRIMARY KEY CLUSTERED ([NotificationId] ASC),
    CONSTRAINT [fkNotification_NotificationProcessTypeId] FOREIGN KEY ([NotificationProcessTypeId]) REFERENCES [Control].[NotificationProcessTypes] ([NotificationProcessTypeId]),
    CONSTRAINT [fkNotification_NotificationSeverity] FOREIGN KEY ([NotificationSeverityId]) REFERENCES [Control].[NotificationSeverity] ([NotificationSeverityId]),
    CONSTRAINT [fkNotification_NotificationStatus] FOREIGN KEY ([NotificationStatusId]) REFERENCES [Control].[NotificationStatus] ([NotificationStatusId]),
    CONSTRAINT [fkNotification_NotificationType] FOREIGN KEY ([NotificationTypeId]) REFERENCES [Control].[NotificationType] ([NotificationTypeId])
);

