




CREATE	view [Test].[JSONRequestStrings]
as
select	N'Invalid JSON' [InvalidJSON]
		,N'{"request":{"type":"GET","entity":"NONE","filters":{},"originator":"automated test","comment":"None"}}' [InvalidRequest]
		,N'{"request":{"type":"GET","entity":"DISTRIBUTIONGROUPS","filters":{},"originator":"automated test","comment":"None"}}' [GetDistributionGroups_All]
		,N'{"request":{"type":"GET","entity":"DISTRIBUTIONGROUPS","filters":{"DistributionGroupCode":"TEST"},"originator":"automated test","comment":"None"}}'	[GetDistributionGroups_TestOnly]
		,N'{"request":{"type":"GET","entity":"DISTRIBUTIONGROUPS","filters":{"DistributionGroupCode":"xxxx"},"originator":"automated test","comment":"None"}}'	[GetDistributionGroups_xxxxOnly]
		,N'{"request":{"type":"GET","entity":"DISTRIBUTIONGROUPS","filters":{"Enabled":"0","DistributionGroupCode":"SKY"},"originator":"automated test","comment":"None"}}' [GetDistributionGroups_DisabledOnly]
		,N'{"request":{"type":"GET","entity":"DISTRIBUTIONGROUPS","filters":{"Enabled":"1"},"originator":"automated test","comment":"None"}}' [GetDistributionGroups_EnabledOnly]	
		,N'{"request":{"type":"GET","entity":"DISTRIBUTIONGROUPS","filters":{"DistributionGroupCode":"TEST","Enabled":"0"},"originator":"automated test","comment":"None"}}' [GetDistributionGroups_TestAndDisabled]	
		,N'{"request":{"type":"GET","entity":"DISTRIBUTIONGROUPS","filters":{"DistributionGroupCode":"TEST","Enabled":"1"},"originator":"automated test","comment":"None"}}' [GetDistributionGroups_TestAndEnabled]	
		,N'{"request":{"type":"GET","entity":"SOCIETIES","filters":{},"originator":"automated test","comment":"None"}}' [GetSocieties_All]
		,N'{"request":{"type":"GET","entity":"SOCIETIES","filters":{"Society":"PRS"},"originator":"automated test","comment":"None"}}' [GetSocieties_PRSOnly]
		,N'{"request":{"type":"GET","entity":"SOCIETIES","filters":{"Enabled":"1"},"originator":"automated test","comment":"None"}}' [GetSocieties_EnabledOnly]
		,N'{"request":{"type":"GET","entity":"SOCIETIES","filters":{"Enabled":"0"},"originator":"automated test","comment":"None"}}' [GetSocieties_DisabledOnly]
		,N'{"request":{"type":"GET","entity":"DISTRIBUTIONS","filters":{},"originator":"automated test","comment":"None"}}' [GetDistributions_All]
		,N'{"request":{"type":"GET","entity":"DISTRIBUTIONS","filters":{"DistributionCode":"DTEST"},"originator":"automated test","comment":"None"}}' [GetDistributions_TestOnly]
		,N'{"request":{"type":"GET","entity":"CALCULATIONGROUP","filters":{},"originator":"automated test","comment":"None"}}' [GetCalculationGroups_All]
		,N'{"request":{"type":"GET","entity":"CALCULATIONGROUP","filters":{"DistributionGroupCode"	:"TEST"},"originator":"automated test","comment":"None"}}' [GetCalculationGroups_TestOnly]
		,N'{"request":{"type":"GET","entity":"STATIONS","filters":{"Society":"PRS","DistributionCode":"DTEST","DistributionGroupCode":"TEST"},"originator":"automated test","comment":"None"}}' [GetStations_TEST_DTEST_PRS_Current]
		,N'{"request":{"type":"GET","entity":"STATIONS","filters":{"Society":"MCPS","DistributionCode":"DTEST","DistributionGroupCode":"TEST"},"originator":"automated test","comment":"None"}}' [GetStations_TEST_DTEST_MCPS_Current]
		,N'{"request":{"type":"GET","entity":"STATIONS","filters":{"Society":"PRS","DistributionCode":"DTEST","DistributionGroupCode":"TEST","TemporalView":"Historical"},"originator":"automated test","comment":"None"}}'  [GetStations_TEST_DTEST_PRS_Historical]
		,N'{"request":{"type":"GET","entity":"CONFIG","filters":{},"originator":"automated test","comment":"None"}}' [GetConfig_ALL_Current]
		,N'{"request":{"type":"GET","entity":"CONFIG","filters":{"TemporalView":"Historical"},"originator":"automated test","comment":"None"}}' [GetConfig_ALL_Historical]
		,N'{"request":{"type":"GET","entity":"CONFIG","filters":{"UsageType":"APPCONFIG"},"originator":"automated test","comment":"None"}}' [GetConfig_APP_Current]
		,N'{"request":{"type":"GET","entity":"CONFIG","filters":{"UsageType":"APPCONFIG","TemporalView":"Historical"},"originator":"automated test","comment":"None"}}' [GetConfig_APP_Historical]
		,N'{"request":{"type":"PUT","entity":"STATIONS","filters":{},"data":[{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST","StationID":"TIR210G","StationName":"SMOOTH READING","StationCategory":"Radio","StationStatus":"Licenced","GroupAdminRate":0.15,"HedgePercent":0.5,"PRAdminRate":0.2,"IsExcluded":false,"Diversity":"No","LowRevenue":"No","AudioPolicyMain":"Census" ,"AudioPolicyCommercial":"Census" ,"CommercialSampleDays":0 ,"NonCommercialSampleDays":0 ,"TotalSampleDays":0,"FPVStatus":"PROG","UpdatedBy":"automated test","UpdateComment":"initial seeding"}
				,{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST","StationID":"TIR2CRG","StationName":"SMOOTH RADIO (BOURNEMOUTH)","StationCategory":"Radio","StationStatus":"Licenced","GroupAdminRate":0.15,"HedgePercent":0.5,"PRAdminRate":0.2,"IsExcluded":false,"Diversity":"No","LowRevenue":"No","AudioPolicyMain":"Census" ,"AudioPolicyCommercial":"Census" ,"CommercialSampleDays":0 ,"NonCommercialSampleDays":0 ,"TotalSampleDays":0,"FPVStatus":"PROG","UpdatedBy":"automated test","UpdateComment":"initial seeding"}
				,{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST1","StationID":"TIR2CRG","StationName":"SMOOTH RADIO (BOURNEMOUTH)","StationCategory":"Radio","StationStatus":"Licenced","GroupAdminRate":0.15,"HedgePercent":0.5,"PRAdminRate":0.2,"IsExcluded":false,"Diversity":"No","LowRevenue":"No","AudioPolicyMain":"Census" ,"AudioPolicyCommercial":"Census" ,"CommercialSampleDays":0 ,"NonCommercialSampleDays":0 ,"TotalSampleDays":0,"FPVStatus":"PROG","UpdatedBy":"automated test","UpdateComment":"initial seeding"}
				,{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST1","StationID":"TIR210G","StationName":"SMOOTH READING","StationCategory":"Radio","StationStatus":"Licenced","GroupAdminRate":0.15,"HedgePercent":0.5,"PRAdminRate":0.2,"IsExcluded":false,"Diversity":"No","LowRevenue":"No","AudioPolicyMain":"Census" ,"AudioPolicyCommercial":"Census" ,"CommercialSampleDays":0 ,"NonCommercialSampleDays":0 ,"TotalSampleDays":0,"FPVStatus":"PROG","UpdatedBy":"automated test","UpdateComment":"initial seeding"}
				,{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST2","StationID":"TIR2CRG","StationName":"SMOOTH RADIO (BOURNEMOUTH)","StationCategory":"Radio","StationStatus":"Licenced","GroupAdminRate":0.15,"HedgePercent":0.5,"PRAdminRate":0.2,"IsExcluded":false,"Diversity":"No","LowRevenue":"No","AudioPolicyMain":"Census" ,"AudioPolicyCommercial":"Census" ,"CommercialSampleDays":0 ,"NonCommercialSampleDays":0 ,"TotalSampleDays":0,"FPVStatus":"PROG","UpdatedBy":"automated test","UpdateComment":"initial seeding"}
				,{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST2","StationID":"TIR210G","StationName":"SMOOTH READING","StationCategory":"Radio","StationStatus":"Licenced","GroupAdminRate":0.15,"HedgePercent":0.5,"PRAdminRate":0.2,"IsExcluded":false,"Diversity":"No","LowRevenue":"No","AudioPolicyMain":"Census" ,"AudioPolicyCommercial":"Census" ,"CommercialSampleDays":0 ,"NonCommercialSampleDays":0 ,"TotalSampleDays":0,"FPVStatus":"PROG","UpdatedBy":"automated test","UpdateComment":"initial seeding"}]}}'[PutStations_InitialSeeding]
		,N'{"request":{"type":"PUT","entity":"STATIONS","filters":{"WithDelete":0},"data":[{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST","StationID":"TIR210G","StationName":"SMOOTH READING","StationCategory":"Radio","StationStatus":"Licenced","GroupAdminRate":0.15,"HedgePercent":0.5,"PRAdminRate":0.3,"IsExcluded":false,"Diversity":"No","LowRevenue":"No","AudioPolicyMain":"Census" ,"AudioPolicyCommercial":"Census" ,"CommercialSampleDays":0 ,"NonCommercialSampleDays":0 ,"TotalSampleDays":0,"FPVStatus":"PROG","UpdatedBy":"automated test","UpdateComment":"update with no delete"}]}}'  [PutStations_UpdateNoDelete]
		,N'{"request":{"type":"PUT","entity":"STATIONS","filters":{"WithDelete":0},"data":[{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST","StationID":"TIR210G","StationName":"SMOOTH READING","StationCategory":"Radio","StationStatus":"Licenced","GroupAdminRate":0.15,"HedgePercent":0.5,"PRAdminRate":0.3,"IsExcluded":false,"Diversity":"No","LowRevenue":"No","AudioPolicyMain":"Census" ,"AudioPolicyCommercial":"Census" ,"CommercialSampleDays":0 ,"NonCommercialSampleDays":0 ,"TotalSampleDays":0,"FPVStatus":"PROG","UpdatedBy":"automated test","UpdateComment":"no update with no delete"}]}}'[PutStations_NoUpdateNoDelete]
		,N'{"request":{"type":"PUT","entity":"STATIONS","filters":{},"data":[{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST1","StationID":"TIR210G","StationName":"SMOOTH READING","StationCategory":"Radio","StationStatus":"Licenced","GroupAdminRate":0.2,"HedgePercent":0.5,"PRAdminRate":0.4,"IsExcluded":false"Diversity":"No","LowRevenue":"No","AudioPolicyMain":"Census" ,"AudioPolicyCommercial":"Census" ,"CommercialSampleDays":0 ,"NonCommercialSampleDays":0 ,"TotalSampleDays":0,"FPVStatus":"PROG","UpdatedBy":"automated test","UpdateComment":"update with delete"}]}}'[PutStations_UpdateWithDelete]
		,N'{"request":{"type":"PUT","entity":"STATIONS","filters":{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST2"}}}'[PutStations_DeleteAllFromCalculationGroup]
		--,N'{"request":{"type":"GET","entity":"REVENUE","filters":{"Society":"PRS","DistributionCode":"DTEST","DistributionGroupCode":"TEST"},"originator":"automated test","comment":"None"}}'[GetRevenue_All]
		,N'{"request":{"type":"GET","entity":"REVENUE","filters":{"Society":"MCPS","DistributionCode":"D181","DistributionGroupCode":"ILR"},"originator":"automated test","comment":"None"}}'[GetRevenue_All]
		--New 2018JUN25 - return Music Minutes ILR D181 - expect > 250
		,N'{"request":{"type":"GET","entity":"MUSICMINUTES","filters":{"Society":"MCPS","DistributionCode":"D181","DistributionGroupCode":"ILR"},"originator":"automated test","comment":"None"}}'[GetMusicMinutes_All]
		--New 2018JUN25 - return Music Minutes ILR D181 - expect > 250
		,N'{"request":{"type":"PUT","entity":"MUSICMINUTES","filters":{"Society":"MCPS","DistributionCode":"D181","DistributionGroupCode":"ILR"},"originator":"automated test","comment":"None"}}'[PutMusicMinutes_All]
		,N'{"request":{"type":"PUT","entity":"REVENUE","filters":{},"data":[{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST","StationID":"TIR210G","Type":"MAIN","Revenue":25000.00,"UpdatedBy":"automated test","UpdateComment":"PutRevenue_TestStationsNoDelete"}
																			,{"Society":"PRS","DistributionGroupCode":"TEST","DistributionCode":"DTEST","StationID":"TIR2CRG","Type":"MAIN","Revenue":25000.00,"UpdatedBy":"automated test","UpdateComment":"PutRevenue_TestStationsNoDelete"}
																			]}}'[PutRevenue_TestStationsNoDelete]
GO


