/*
NotificationTemplates
A template is required for each notification the system will send.
This table defines the name of the template and the content, including placeholders. When a notification is processed, the placeholders are replaced with items of data that are
logged when the notification is requested.
*/
with NotificationTemplate as (
select [templateName],[category],[enabled],[profileName],[greeting],[bodyText],[signature]
from (values 
 ('MDS Station Changes','HTMLEMAIL',1,'AZI-MS-SQL-U001 SQL Database Mail','<BR>','<html><head><style> body {  background-color: #D8D8D8;}table {    width:500;    font-family:"Segoe UI";   align="center";  }table, th, td {    border: 1px solid black;    border-collapse: collapse;}th, td {    padding: 25px;}</style></head>  <!-- <h2><font face="Segoe UI"> Email content</font></h2>--><br><table id="t01">   <tr>    <!-- <th align="left"><p><font face="Comic sans MS" color="green">PRS Master Data Management</font></p></th>-->    <th align="left"  bgcolor="white" ><h3>PRS Master Data Management</h3></th>  <!--https://www.prsformusic.com/press/2018/record-royalties-paid-to-songwriters-and-composers-->      <!--Other email content-->    </p>  </tr>  <tr>    <td align="center" bgcolor="black" style="color: white;">      <p><h3>Master Station Data Changes from REP & CRM #Date#</h3>         <font size="2">         <p>&nbsp;</p>        <strong>New Stations REP: #NewREP# </strong>        <br>These stations have been added to MDS. Please review and update outstanding fields.</br>        <p>&nbsp;</p>    <strong>New Stations CRM: #NewCRM# </strong>        <br>These stations have been added to MDS. Please review and update outstanding fields.</br>        <p>&nbsp;</p>  <strong>New MDS Station: #NewMDS# </strong>   <br>These stations have been created in MDS but dont exist in REP. Please review and update outstanding fields.</br>        <p>&nbsp;</p>   <strong>Updates to existing stations from REP: #UpdatedREP# </strong>        <br>These changes are pending approval. Please make the necessary changes to either the master data in MDS, or the source data in REP.</br>        <p>&nbsp;</p>   </font>         <p>&nbsp;</p>         <font size="1" >In accordance with the agreed data governance process, please review the above changes and ensure all updates are made.</font>         </p></td>  </tr>  <tr>    <td align="center"  bgcolor="white" >Full details about these pending changes<br><a href=#ReportLink#>Check it out</a></br></tr><tr>  <td bgcolor="#F2F3F4" style="color: #273746;"><h2>PRS BI Team</h2>  </td></tr></table></body></html>','<BR> Regards, <BR> PRS BI Team')
,('MDS Validation SDM','HTMLEMAIL',1,'AZI-MS-SQL-U001 SQL Database Mail','<BR>','<html><head><style> body {  background-color: #D8D8D8;}table {    width:500;    font-family:"Segoe UI";   align="center";  }table, th, td {    border: 1px solid black;    border-collapse: collapse;}th, td {    padding: 25px;}</style></head>  <!-- <h2><font face="Segoe UI"> Email content</font></h2>--><br><table id="t01">   <tr><!-- <th align="left"><p><font face="Comic sans MS" color="green">PRS Master Data Management</font></p></th>-->    <th align="left"  bgcolor="white" ><h3>PRS Master Data Management</h3></th>  <!--https://www.prsformusic.com/press/2018/record-royalties-paid-to-songwriters-and-composers--><!--Other email content-->    </p>  </tr>  <tr>    <td align="center" bgcolor="black" style="color: white;"><p><h3>MDS Validation Report #Date#</h3>  <p>&nbsp;</p><strong>This is the daily MDS validation notification which provides alerting to potential invalid data conditions within MDS.</strong>   <br><strong>In accordance with the agreed data governance process, please review the above changes and ensure all updates are made.</strong></br>  <br>#LicenceUpdate# Licence group updates has been made to the MDS.</br><br>#AudioPolicyUpdates# Audio Policy updates has been made the MDS.</br><br>#ValidationBreaks# stations breaks Validation Rule.</br></td> </tr><tr><td align="center"  bgcolor="white" >Full details can be found by following the report link below<br><a href=#ReportLink#>MDS Validation Report (SDM)</a></br></tr><tr>  <td bgcolor="#F2F3F4" style="color: #273746;"><h2>PRS BI Team</h2>  </td></tr></table></body></html>','<BR> Regards, <BR> PRS BI Team')
,('MDS Validation Licencing','HTMLEMAIL',1,'AZI-MS-SQL-U001 SQL Database Mail','<BR>','<html><head><style> body {  background-color: #D8D8D8;}table {    width:500;    font-family:"Segoe UI";   align="center";  }table, th, td {    border: 1px solid black;    border-collapse: collapse;}th, td {    padding: 25px;}</style></head>  <!-- <h2><font face="Segoe UI"> Email content</font></h2>--><br><table id="t01">   <tr><!-- <th align="left"><p><font face="Comic sans MS" color="green">PRS Master Data Management</font></p></th>-->    <th align="left"  bgcolor="white" ><h3>PRS Master Data Management</h3></th>  <!--https://www.prsformusic.com/press/2018/record-royalties-paid-to-songwriters-and-composers--><!--Other email content-->    </p>  </tr>  <tr>    <td align="center" bgcolor="black" style="color: white;"><p><h3>MDS Validation Report #Date#</h3>    <p>&nbsp;</p><strong>This is the daily MDS validation notification which provides alerting to potential invalid data conditions within MDS.</strong>   <br><strong>In accordance with the agreed data governance process, please review the above changes and ensure all updates are made.</Strong></br>  <br>#ValidationBreaks# stations breaks Validation Rule.</br><br>#LicenceFeeBreaks# Licence Fee was validated.</br><br>#AttributeMismatches# mapped licencing attribute does not match with MDS counterpart.</br></td> </tr><tr><td align="center"  bgcolor="white" >Full details can be found by following the report link below<br><a href=#ReportLink#>MDS Validation Report (Licencing)</a></br></tr><tr>  <td bgcolor="#F2F3F4" style="color: #273746;"><h2>PRS BI Team</h2>  </td></tr></table></body></html>','<BR> Regards, <BR> PRS BI Team')
,('MDS Validation BI','HTMLEMAIL',1,'AZI-MS-SQL-U001 SQL Database Mail','<BR>','<html><head><style> body {  background-color: #D8D8D8;}table {    width:500;    font-family:"Segoe UI";   align="center";  }table, th, td {    border: 1px solid black;    border-collapse: collapse;}th, td {    padding: 25px;}</style></head>  <!-- <h2><font face="Segoe UI"> Email content</font></h2>--><br><table id="t01">   <tr><!-- <th align="left"><p><font face="Comic sans MS" color="green">PRS Master Data Management</font></p></th>-->    <th align="left"  bgcolor="white" ><h3>PRS Master Data Management</h3></th>  <!--https://www.prsformusic.com/press/2018/record-royalties-paid-to-songwriters-and-composers--><!--Other email content-->    </p>  </tr>  <tr>    <td align="center" bgcolor="black" style="color: white;"><p><h3>MDS Validation Report #Date#</h3>         <p>&nbsp;</p><strong>This is the daily MDS validation notification which provides alerting to potential invalid data conditions within MDS.</Strong>         <br><Strong>In accordance with the agreed data governance process, please review the above changes and ensure all updates are made.<Strong></br>  <br>#ValidationBreaks# stations breaks Validation Rule.</br></td> </tr><tr><td align="center"  bgcolor="white" >Full details can be found by following the report link below<br><a href=#ReportLink#>MDS Validation Report (BI)</a></br></tr><tr>  <td bgcolor="#F2F3F4" style="color: #273746;"><h2>PRS BI Team</h2>  </td></tr></table></body></html>','<BR> Regards, <BR> PRS BI Team')
,('Distribution Data Integration','HTMLEMAIL',1,'AZI-MS-SQL-U001 SQL Database Mail','<BR>','<html><head><style> body {  background-color: #D8D8D8;}table {    width:500;    font-family:"Segoe UI";   align="center";  }table, th, td {    border: 1px solid black;    border-collapse: collapse;}th, td {    padding: 25px;}</style></head>  <!-- <h2><font face="Segoe UI"> Email content</font></h2>--><br><table id="t01">   <tr><!-- <th align="left"><p><font face="Comic sans MS" color="green">PRS Master Data Management</font></p></th>-->    <th align="left"  bgcolor="white" ><h3>PRS Master Data Management</h3></th>  <!--https://www.prsformusic.com/press/2018/record-royalties-paid-to-songwriters-and-composers--><!--Other email content-->    </p>  </tr>  <tr>    <td align="center" bgcolor="black" style="color: white;"><p><h3>Distribution Data Integration #Date#</h3></p><br>#MusicMinutes# unmatched/unknown station(s) have been identified in Music Minutes.</br><br>#MissingMinutes# unmatched/unknown stations have been identified in Missing Minutes.</br><br>#PublicReception# unmatched/unknown stations have been identified in Public Reception.</br>   <br><Strong>Please review stations listed on the detail report and add to Master Data / remove from source file where appropriate.</strong></br><br></td> </tr><tr><td align="center"  bgcolor="white" >Full details can be found by following the report link below<br><a href=#ReportLink#>Distributed Data Integration</a></br></tr><tr>  <td bgcolor="#F2F3F4" style="color: #273746;"><h2>PRS BI Team</h2>  </td></tr></table></body></html>','<BR> Regards, <BR> PRS BI Team')
,('MDS Supplied Station','HTMLEMAIL',1,'AZI-MS-SQL-U001 SQL Database Mail','<BR>','<html><head><style> body {  background-color: #D8D8D8;}table {    width:500;    font-family:"Segoe UI";   align="center";  }table, th, td {    border: 1px solid black;    border-collapse: collapse;}th, td {    padding: 25px;}</style></head>  <!-- <h2><font face="Segoe UI"> Email content</font></h2>--><br><table id="t01">   <tr><!-- <th align="left"><p><font face="Comic sans MS" color="green">PRS Master Data Management</font></p></th>-->    <th align="left"  bgcolor="white" ><h3>PRS Master Data Management</h3></th>  <!--https://www.prsformusic.com/press/2018/record-royalties-paid-to-songwriters-and-composers--><!--Other email content-->    </p>  </tr>  <tr>    <td align="center" bgcolor="black" style="color: white;"><p><h3>Issues found when updating MDS from external data sources (BARB;RAJAR) #Date#</h3></p><br>#UnmatchedBARB# Unmatched BARB stations.</br><br>#UnmatchedRAJAR# Unmatched RAJAR stations.</br>  <br><font size="2" >(A station is unmatched when a new station from sourcefile has not been previously matched to MDS)</font></br><br>#UnknownBARB# Unknown BARB stations.</br><br>#UnknownRAJAR# Unknown RAJAR stations.</br><br><font size="2" >(A station is unknown when it is marked as unknown by user)</font></br>  <p>&nbsp;</p>         <font size="2" >In accordance with the agreed data governance process, please review the above changes and ensure all updates are made.</font>         </p></td> </tr><tr><td align="center"  bgcolor="white" >Full details can be found by following the report link below<br><a href=#ReportLink#>MDS Supplied Station</a></br></tr><tr>  <td bgcolor="#F2F3F4" style="color: #273746;"><h2>PRS BI Team</h2>  </td></tr></table></body></html>','<BR> Regards, <BR> PRS BI Team')
,('Station UDC Validation','HTMLEMAIL',1,'AZI-MS-SQL-U001 SQL Database Mail','<BR>','<html><head><style> body {  background-color: #D8D8D8;}table {    width:500;    font-family:"Segoe UI";   align="center";  }table, th, td {    border: 1px solid black;    border-collapse: collapse;}th, td {    padding: 25px;}</style></head>  <!-- <h2><font face="Segoe UI"> Email content</font></h2>--><br><table id="t01">   <tr><!-- <th align="left"><p><font face="Comic sans MS" color="green">PRS Master Data Management</font></p></th>-->    <th align="left"  bgcolor="white" ><h3>PRS Master Data Management</h3></th>  <!--https://www.prsformusic.com/press/2018/record-royalties-paid-to-songwriters-and-composers--><!--Other email content-->    </p>  </tr>  <tr>    <td align="center" bgcolor="black" style="color: white;"><p><h3>Master Station Data Changes #Date#</h3></p><br>#MDSRep# specified stations not existing in REP.</br><br>#MDSDandM# specified stations not existing in D&M.</br><br>#NotInMDS# specified stations not in MDS.</br></td> </tr><tr><td align="center"  bgcolor="white" >Full details can be found by following the report link below<br><a href=#ReportLink#>Station UDC Validation</a></br></tr><tr>  <td bgcolor="#F2F3F4" style="color: #273746;"><h2>PRS BI Team</h2>  </td></tr></table></body></html>','<BR> Regards, <BR> PRS BI Team')
,('Analogy Station Integration','HTMLEMAIL',1,'AZI-MS-SQL-U001 SQL Database Mail','<BR>','<html><head><style> body {  background-color: #D8D8D8;}table {    width:500;    font-family:"Segoe UI";   align="center";  }table, th, td {    border: 1px solid black;    border-collapse: collapse;}th, td {    padding: 25px;}</style></head>  <!-- <h2><font face="Segoe UI"> Email content</font></h2>--><br><table id="t01">   <tr><!-- <th align="left"><p><font face="Comic sans MS" color="green">PRS Master Data Management</font></p></th>-->    <th align="left"  bgcolor="white" ><h3>PRS Master Data Management</h3></th>  <!--https://www.prsformusic.com/press/2018/record-royalties-paid-to-songwriters-and-composers--><!--Other email content-->    </p>  </tr>  <tr>    <td align="center" bgcolor="black" style="color: white;"><p><h3>Master Station Data Changes</h3>     <p>&nbsp;</p><strong>Updates to existing stations [Analagy Station ID]</strong>        <br>Analogy Station updates have been made to #Updates# existing Master Stations.</br> <br><strong>Further Analogy Station updates were not made because:</strong></br>   <br>#UnmatchedMasterStations# specified Master Stations could not be found in MDS</br><br>#UnmatchedAnalogyStations# specified Analogy Stations could not be found in MDS</br><p>&nbsp;</p><font size="1" >In accordance with the agreed data governance process, please review the above changes and ensure all updates are made.</font></p></td>  </tr>  <tr>    <td align="center"  bgcolor="white" >Full details can be found by following the report link below<br><a href=#ReportLink#>Analogy Station Updates</a></br></tr><tr>  <td bgcolor="#F2F3F4" style="color: #273746;"><h2>PRS BI Team</h2>  </td></tr></table></body></html>','<BR> Regards, <BR> PRS BI Team')
,('MDS Validation Finance','HTMLEMAIL',1,'AZI-MS-SQL-U001 SQL Database Mail','<BR>','<html><head><style> body {  background-color: #D8D8D8;}table {    width:500;    font-family:"Segoe UI";   align="center";  }table, th, td {    border: 1px solid black;    border-collapse: collapse;}th, td {    padding: 25px;}</style></head>  <!-- <h2><font face="Segoe UI"> Email content</font></h2>--><br><table id="t01">   <tr>    <!-- <th align="left"><p><font face="Comic sans MS" color="green">PRS Master Data Management</font></p></th>-->    <th align="left"  bgcolor="white" ><h3>PRS Master Data Management</h3></th>  <!--https://www.prsformusic.com/press/2018/record-royalties-paid-to-songwriters-and-composers-->      <!--Other email content-->    </p>  </tr>  <tr> <td align="center" bgcolor="black" style="color: white;"> <p><h3>MDS Validation Report #NDate#</h3><br>This is the daily MDS validation notification which provides alerting to potential invalid data conditions within MDS.</br><br>In accordance with the agreed data governance process, please review the above changes and ensure all updates are made.</br><p>&nbsp;</p><br>#NullEL2Codes# stations have NULL EL2 Codes.</br><br>#NullCodaCustomerCodes# stations have NULL Coda Customer Codes.</br></td> </tr><tr><td align="center"  bgcolor="white" >Full details can be found by following the report link below<br><a href=#ReportLink#>MDS Validation Report (Finance)</a></br></tr><tr>  <td bgcolor="#F2F3F4" style="color: #273746;"><h2>PRS BI Team</h2>  </td></tr></table></body></html>','<BR> Regards, <BR> PRS BI Team')
	)t([templateName],[category],[enabled],[profileName],[greeting],[bodyText],[signature])
)
merge notification.[template] t
using NotificationTemplate s
on s.[templateName]=t.[templateName]

when not matched then
insert ([templateName],[category],[enabled],[profileName],[greeting],[bodyText],[signature])
values (s.[templateName],s.[category],s.[enabled],s.[profileName],s.[greeting],s.[bodyText],s.[signature])

when matched then
update set t.[category]=s.[category]
			,t.[enabled]=s.[enabled]
			,t.[profileName]=s.[profileName]
			,t.[greeting]=s.[greeting]
			,t.[bodyText]=s.[bodyText]
			,t.[signature]=s.[signature];