
CREATE FUNCTION [Config].[udfGetNums](@Start INT, @End INT)
RETURNS TABLE
RETURN
-- Return specified range of numbers.
	WITH Num1(n) AS
	(
		SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
		SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
		SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1
	),
		Num2(n) AS (SELECT 1 FROM Num1 CROSS JOIN Num1 AS b),			 
		Num3(n) AS (SELECT 1 FROM Num2 CROSS JOIN Num2 AS c),			 
		Num4(n) AS (SELECT 1 FROM Num3 CROSS JOIN Num3 AS d)			 
	SELECT n = ROW_NUMBER() OVER (ORDER BY n) FROM Num4 ORDER BY n
	OFFSET @Start -1  ROWS FETCH NEXT @End - @Start + 1 ROWS ONLY;