CREATE TABLE [Audit].[ExecutionLogs] (
    [ExecutionLogId]            UNIQUEIDENTIFIER NOT NULL,
    [ReportKey]                 INT              NOT NULL,
    [UserKey]                   INT              NOT NULL,
    [MachineKey]                INT              NOT NULL,
    [RequestType]               INT              NOT NULL,
    [FormatType]                INT              NOT NULL,
    [StatusCode]                INT              NOT NULL,
    [SourceType]                INT              NOT NULL,
    [TimeStart]                 DATETIME         NOT NULL,
    [TimeEnd]                   DATETIME         NOT NULL,
    [TimeDataRetrieval]         INT              NOT NULL,
    [TimeProcessing]            INT              NOT NULL,
    [TimeRendering]             INT              NOT NULL,
    [ByteCount]                 BIGINT           NOT NULL,
    [RowCount]                  BIGINT           NOT NULL,
    [ExecutionId]               NVARCHAR (64)    NOT NULL,
    [TotalExecTime]             INT              NOT NULL,
    [ActionType]                INT              NOT NULL,
    [ScalabilityTimePaging]     INT              NOT NULL,
    [ScalabilityTimeProcessing] INT              NOT NULL,
    [EstMemoryKBPaging]         INT              NOT NULL,
    [EstMemoryKBProcessing]     INT              NOT NULL,
    [CreatedBy]                 [sysname]        DEFAULT (suser_sname()) NOT NULL,
    [CreatedDate]               DATETIME         DEFAULT (getdate()) NOT NULL,
    [UpdatedBy]                 [sysname]        DEFAULT (suser_sname()) NOT NULL,
    [UpdatedDate]               DATETIME         DEFAULT (getdate()) NOT NULL,
    [RowVersion]                ROWVERSION       NOT NULL,
    CONSTRAINT [pkcExecutionLogs] PRIMARY KEY CLUSTERED ([ExecutionLogId] ASC)
);

