CREATE TABLE [Control].[SourceFile] (
    [SourceFileId]				INT              IDENTITY (1, 1) NOT NULL,
    [ParentSourceFileId]		INT              NULL,
    [SourceFileName]			NVARCHAR (255)   NOT NULL,
    [SourceFileTypeId]			INT              NULL,
    [FileExtensionTypeId]		SMALLINT         NULL,
	[ApplicationId]				SMALLINT         NULL,
	[OriginalFileId]			INT              NULL,
    [ModifiedDate]				DATETIME         NOT NULL,
    [FileSizeBytes]				BIGINT           NOT NULL,
    [DataSourceType]			VARCHAR (100)    NULL,
    [IsCompressed]				BIT              NULL,
    [Source]					VARCHAR (400)    NULL,
    [FileExtractedDate]			DATETIME         NULL,
	[FileExtractedParentLoadId] INT				 NULL,
	[BlobUploadDate]			DATETIME         NULL,
    [StageDate]					DATETIME         NULL,
	[StageParentLoadId]			INT				 NULL,
    [CleanDate]					DATETIME         NULL,
	[CleanParentLoadId]			INT				 NULL,
	[TransformDate]				DATETIME         NULL,
	[TransformParentLoadId]		INT				 NULL,
    [WarehouseDate]				DATETIME         NULL,
	[WarehouseParentLoadId]		INT				 NULL,
    [OLAPDate]					DATETIME         NULL,
    [ArchivePath]				NVARCHAR (400)   NULL,
    [ArchiveDate]				DATETIME         NULL,
    [UnloadFile]				BIT              DEFAULT ((0)) NULL,
    [FileUnloaded]				BIT              NULL,
    [FileUnloadedDate]			DATETIME         NULL,
    [LoadId]					INT              NULL,
    [CreatedBy]					[sysname]        DEFAULT (suser_sname()) NOT NULL,
    [CreatedDate]				DATETIME         DEFAULT (getdate()) NOT NULL,
	[TotalNoOfUses]				BIGINT				NULL,
	[32BitStageRequired]		BIT					DEFAULT ((0)) NULL,
	[MDSDate]                   DATETIME			NULL,
	[ScrubDate]                 DATETIME			NULL,
	[LDSDate]                   DATETIME			NULL,
	[PartitionKey]              INT					NULL,
	[PurgeFromArchive]          BIT					DEFAULT ((0)) NULL,
    [ArchivePurged]             BIT					NULL,
    [ArchivePurgedDate]         DATETIME			NULL,
	[PreStageDate]              DATETIME			NULL,
	[IsLoaded]			        BIT					NULL,
	[IsToBeLoaded]		        BIT					NULL,
	[SourceFileType]	        NVARCHAR(255)		NULL,


    CONSTRAINT [pkcSourceFileId] PRIMARY KEY CLUSTERED ([SourceFileId] ASC),
    CONSTRAINT [fkSourceFile_ExtensionType] FOREIGN KEY ([FileExtensionTypeId]) REFERENCES [Control].[FileExtensionType] ([FileExtensionTypeId]),
    CONSTRAINT [fkSourceFile_SourceFile] FOREIGN KEY ([ParentSourceFileId]) REFERENCES [Control].[SourceFile] ([SourceFileId]),
    CONSTRAINT [fkSourceFile_SourceFileType] FOREIGN KEY ([SourceFileTypeId]) REFERENCES [Control].[SourceFileType] ([SourceFileTypeId]),
	CONSTRAINT [fkSourceFile_Application] FOREIGN KEY ([ApplicationId]) REFERENCES [Control].[Application] ([ApplicationId])
);

