CREATE TABLE [SSIS].[executions] (
	[execution_id] bigint IDENTITY (1, 1) NOT NULL,
    [folder_name] sysname NOT NULL ,
    [project_name] sysname NOT NULL ,
    [package_name] nvarchar(260) NOT NULL ,
    [reference_id] bigint ,
    [reference_type] char(1) ,
    [environment_folder_name] nvarchar(128) ,
    [environment_name] nvarchar(128) ,
    [project_lsn] bigint ,
    [executed_as_sid] varbinary(85) NOT NULL ,
    [executed_as_name] nvarchar(128) NOT NULL ,
    [use32bitruntime] bit NOT NULL ,
    [operation_type] smallint NOT NULL ,
    [created_time] datetimeoffset(7) ,
    [object_type] smallint ,
    [object_id] bigint ,
    [status] int ,
    [start_time] datetimeoffset(7) ,
    [end_time] datetimeoffset(7) ,
    [caller_sid] varbinary(85) ,
    [caller_name] sysname NOT NULL ,
    [process_id] int ,
    [stopped_by_sid] varbinary(85) ,
    [stopped_by_name] nvarchar(128) ,
    [dump_id] uniqueidentifier ,
    [server_name] nvarchar(128) ,
    [machine_name] nvarchar(128) ,
    [total_physical_memory_kb] bigint ,
    [available_physical_memory_kb] bigint ,
    [total_page_file_kb] bigint ,
    [available_page_file_kb] bigint ,
    [cpu_count] int,
);

