
CREATE VIEW [TM1reporting].[ImportFileLog]
as
	SELECT [FileLogUniqueKey]
		  ,[FileRawRowCount]
		  ,[FileCreatedTimeStamp]
		  ,[FileModifiedTimeStamp]
		  ,[FilePath]
		  ,[FileName]
		  ,[FileSource]
		  ,[FileStartPeriodString]
		  ,[FileEndPeriodString]
		  ,[FileStartPeriodSeq]
		  ,[FileEndPeriodSeq]
		  ,[FileTypeKey] as [RevenueFileTypeKey]
		  ,[DerivedFileType]
		  ,[FileSize]
		  ,[SourceFileID]
		  ,[SourceFileInsertTimeStamp]
		  ,[StagingValidToLoadFlag]
		  ,[StagingStartPeriodSeq]
		  ,[StagingEndPeriodSeq]
		  ,[StagingTotalRows]
		  ,[StagingValidValue]
		  ,[StagingValidStatus]
		  ,[StagingTimeStamp]
		  ,[TransformTimeStamp]
		  ,[TransformValidValue]
		  ,[TransformValidRows]
		  ,[TransformValidStatus]
		  ,[ExtractFDMTimeStamp]
		  ,[ExtractFDMValue]
		  ,[ExtractFDMRows]
		  ,[ExtractFPVTimeStamp]
		  ,[ExtractFPVValue]
		  ,[ExtractFPVRows]
		  ,[ExtractValidStatus]
		  ,[FileMovedAtSourceFlag]
		  ,[FileMovedActionTaken]
		  ,[FileMovedTimeStamp]
		  ,[FileMovedDestinationFolder]
		  ,[FileDeletedLoadId]
		  ,[FileDeletedTimeStamp]
		  ,[LoadId]
		  ,[LoadTimeStamp]
	  FROM [FinanceStage].[TM1Control].[ImportFileLog]