CREATE VIEW TM1Reporting.[PlanningData]
as
	SELECT [PlanningDataKey]
      ,[PlanningScenarioKey]
      ,[PlanningFileLogKey]
      ,[PlanningFileTypeKey]
      ,[PlanningCalendarKey]
      ,[PlanningFilePeriodSeq]
      ,[PlanningPeriodFirstDay]
      ,[Company]
      ,[Class]
      ,[Level4]
      ,[Level3]
      ,[Level2]
      ,[Level1]
      ,[EL1Description]
      ,[EL1Code]
      ,[EL2Description]
      ,[EL2Code]
      ,[PlanningPeriod]
      ,[PlanningYear]
      ,[PlanningScenario]
      ,[ValueGBP]
      ,[InsertTimeStamp]
      ,[InsertLoadId]
  FROM [FinanceStage].[TM1Transform].[PlanningData]