/*
Deployment script for Hector2

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Hector2"
:setvar DefaultFilePrefix "Hector2"
:setvar DefaultDataPath "F:\SQLServerDatabases\"
:setvar DefaultLogPath "G:\SQLServerXLogs\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];

GO
CREATE TABLE [HctrStaging].[BaseRevenueTM1] (
    [TM1BaseRevenueKey]          INT           IDENTITY (1, 1) NOT NULL,
    [CompanyCode]                VARCHAR (50)  NULL,
    [AccountCodeEL1]             VARCHAR (150) NULL,
    [AccountCodeEL2]             VARCHAR (150) NULL,
    [AccountCompanyCodeEL1]      VARCHAR (50)  NULL,
    [AccountCompanyCodeEL2]      VARCHAR (50)  NULL,
    [PlanningScenario]           VARCHAR (50)  NULL,
    [PlanningPeriod]             VARCHAR (50)  NULL,
    [PlanningYear]               VARCHAR (50)  NULL,
    [PlanningFilePeriodSeq]      INT           NULL,
    [PlanningPeriodFirstDay]     DATETIME2 (2) NULL,
    [TM1CategoryOnlineBroadcast] VARCHAR (150) NULL,
    [TM1BroadcastGroup]          VARCHAR (150) NULL,
    [ValueGBP]                   MONEY         NULL,
    [TM1PlanningFileLogKey]      INT           NULL,
    [InsertLoadId]               INT           NULL,
    [InsertTimeStamp]            DATETIME      NULL,
    CONSTRAINT [PK_BaseRevenue] PRIMARY KEY CLUSTERED ([TM1BaseRevenueKey] ASC)
);


GO
PRINT N'Creating [HctrStaging].[DF_BaseRevenueTM1_InsertTimeStamp]...';


GO
ALTER TABLE [HctrStaging].[BaseRevenueTM1]
    ADD CONSTRAINT [DF_BaseRevenueTM1_InsertTimeStamp] DEFAULT (getdate()) FOR [InsertTimeStamp];


GO
PRINT N'Creating [HctrMDSIn].[MstrTM1Scenario]...';


GO

create view [HctrMDSIn].MstrTM1Scenario
as

SELECT [RevisionID]
      ,[State]
      --,[ID]
      --,[MUID]
      ,[Name]
      ,[Code]
      ,[EnterDateTime]
      ,[EnterUserName]
      ,[LastChgDateTime]
      ,[LastChgUserName]
  FROM [MDS].[mdm].[hctr_MstrTM1Scenario]
    where [LastChgUserName] is null
GO
PRINT N'Update complete.';


GO
